import type { ToolCreationV1Result } from "./toolCreationV1.js";
import type { ToolPackageManifest } from "./toolPackage.js";

export function renderExternalActionCommitToolSource(
  input: ToolCreationV1Result["input"],
  manifest: Omit<ToolPackageManifest, "package">,
): string {
  return [
    "import { existsSync, readdirSync } from \"node:fs\";",
    "import { homedir } from \"node:os\";",
    "import { join } from \"node:path\";",
    "import { chromium, type Locator, type Page } from \"playwright-core\";",
    "import type { Tool } from \"../tool.js\";",
    "",
    `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
    `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
    "",
    "export const tool: Tool = {",
    `  name: ${JSON.stringify(input.name)},`,
    `  displayName: ${JSON.stringify(input.displayName)},`,
    `  version: ${JSON.stringify(input.version)},`,
    `  description: ${JSON.stringify(input.description)},`,
    `  capabilities: ${JSON.stringify(input.capabilities)},`,
    `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
    "  inputSchema,",
    "  outputSchema,",
    "  async healthcheck() {",
    "    return { ok: true, detail: \"External action commit executor loaded.\" };",
    "  },",
    "  async run(input, context) {",
    "    const proposalId = readString(input, \"proposalId\");",
    "    const actionType = readString(input, \"actionType\");",
    "    const proposedAction = input.proposedAction;",
    "    const hasProposedAction =",
    "      typeof proposedAction === \"string\" ? proposedAction.trim().length > 0 : Boolean(readRecord(proposedAction));",
    "    const missing = [",
    "      proposalId ? undefined : \"proposalId\",",
    "      actionType ? undefined : \"actionType\",",
    "      hasProposedAction ? undefined : \"proposedAction\",",
    "    ].filter((item): item is string => Boolean(item));",
    "    if (missing.length > 0) {",
    "      return blocked(\"missing required commit input\", input, { missing });",
    "    }",
    "    const confirmation = readFixtureConfirmation(input);",
    "    const fixtureCommit = await commitLocalFixtureIfAvailable(input, confirmation);",
    "    if (fixtureCommit && !fixtureCommit.ok) {",
    "      return {",
    "        ok: false,",
    "        content: fixtureCommit.content,",
    "        data: fixtureCommit.data,",
    "      };",
    "    }",
    "    if (fixtureCommit?.ok || confirmation) {",
    "      const providerResponse = fixtureCommit?.data ?? confirmation;",
    "      return {",
    "        ok: true,",
    "        content: `Committed fixture external action ${proposalId}: ${readString(providerResponse, \"confirmationId\") ?? confirmation?.confirmationId}` ,",
    "        data: {",
    "          provider: readString(providerResponse, \"provider\") ?? confirmation?.provider ?? \"fixture\",",
    "          confirmationId: readString(providerResponse, \"confirmationId\") ?? confirmation?.confirmationId,",
    "          proposalId,",
    "          actionType,",
    "          preparedUrl: readPreparedUrl(input),",
    "          artifactIds: readStringArray(input.artifactIds),",
    "          submittedPayloadSummary: readString(providerResponse, \"submittedPayloadSummary\") ?? summarizeValue(proposedAction),",
    "          providerResponse,",
    "        },",
    "      };",
    "    }",
    "    return commitPreparedBrowserSession(input, context);",
    "  },",
    "};",
    "",
    "const COMMIT_TEXT = /(book|reserve|reservation|confirm|submit|send|schedule|appointment|finish|continue|done|complete|reservar|confirmar|enviar|continuar|cita|finalizar|hecho|siguiente)/i;",
    "const SAFE_REPLAY_ACTIONS = new Set([\"dismissdialogs\", \"dismissdialog\", \"fill\", \"type\", \"select\", \"selectoption\", \"waitforselector\", \"waitfortext\", \"click\"]);",
    "",
    "async function commitPreparedBrowserSession(input: Record<string, unknown>, context: unknown) {",
    "  const preparedUrl = readPreparedUrl(input);",
    "  const replaySteps = readRecords(input.replaySteps);",
    "  const preparedSession = readRecord(input.preparedSession);",
    "  const commitCandidates = readRecords(preparedSession?.commitCandidates ?? input.commitCandidates);",
    "  if (!preparedUrl) {",
    "    return blocked(\"missing_requirements: preparedSession.currentUrl is required for generic browser commit\", input, { missing: [\"preparedSession.currentUrl\"] });",
    "  }",
    "  if (!commitCandidates.length) {",
    "    return blocked(\"missing_requirements: no commit candidate was detected in the prepared form\", input, { missing: [\"preparedSession.commitCandidates\"] });",
    "  }",
    "  const browser = await chromium.launch(browserLaunchOptions());",
    "  const steps: Array<Record<string, unknown>> = [];",
    "  const artifacts: Array<Record<string, unknown>> = [];",
    "  try {",
    "    const page = await browser.newPage({ viewport: { width: 1365, height: 900 } });",
    "    page.setDefaultTimeout(15000);",
    "    await page.goto(preparedUrl, { waitUntil: \"domcontentloaded\", timeout: 20000 });",
    "    steps.push({ action: \"navigate\", ok: true, detail: page.url() });",
    "    for (const command of replaySteps.slice(0, 40)) {",
    "      const step = await replayCommand(page, command, input);",
    "      if (step) steps.push(step);",
    "      if (step && step.ok === false && command.optional !== true) {",
    "        return blocked(`missing_requirements: replay step failed before final submit: ${step.detail}`, input, { missing: [\"replay_step_failed\"], steps });",
    "      }",
    "    }",
    "    const before = await captureArtifact(page, input, \"before-submit\");",
    "    artifacts.push(before);",
    "    await saveArtifact(context, before);",
    "    const clicked = await clickCommitCandidate(page, commitCandidates);",
    "    if (!clicked.ok) {",
    "      return blocked(String(clicked.detail ?? \"missing_requirements: no clickable commit candidate matched the prepared form\"), input, { missing: [\"clickable_commit_candidate\"], steps, artifacts });",
    "    }",
    "    steps.push(clicked);",
    "    await page.waitForLoadState(\"domcontentloaded\", { timeout: 15000 }).catch(() => undefined);",
    "    await page.waitForTimeout(1200);",
    "    const after = await captureArtifact(page, input, \"after-submit\");",
    "    artifacts.push(after);",
    "    await saveArtifact(context, after);",
    "    const text = compactText(await page.locator(\"body\").innerText({ timeout: 5000 }).catch(() => \"\"), 2000);",
    "    const confirmationId = inferConfirmationId(text) ?? `browser-${Date.now()}`;",
    "    return {",
    "      ok: true,",
    "      content: `Submitted approved external action ${readString(input, \"proposalId\") ?? \"proposal\"}; confirmation evidence captured from ${page.url()}` ,",
    "      data: {",
    "        provider: new URL(page.url()).hostname,",
    "        confirmationId,",
    "        status: \"submitted_or_confirmation_page_reached\",",
    "        proposalId: readString(input, \"proposalId\"),",
    "        actionType: readString(input, \"actionType\"),",
    "        preparedUrl,",
    "        finalUrl: page.url(),",
    "        clickedCandidate: clicked.candidate,",
    "        submittedPayloadSummary: submittedPayloadSummary(input),",
    "        confirmationTextPreview: text,",
    "        steps,",
    "        artifacts,",
    "      },",
    "    };",
    "  } finally {",
    "    await browser.close();",
    "  }",
    "}",
    "",
    "async function replayCommand(page: Page, command: Record<string, unknown>, input: Record<string, unknown>): Promise<Record<string, unknown> | undefined> {",
    "  const action = commandName(command);",
    "  if (!SAFE_REPLAY_ACTIONS.has(action)) return undefined;",
    "  if (action === \"click\" && COMMIT_TEXT.test(targetText(command)) && command.allowCommit !== true) {",
    "    return { action, ok: true, skipped: true, detail: \"skipped possible final submit click until commit phase\" };",
    "  }",
    "  try {",
    "    if (action === \"dismissdialogs\" || action === \"dismissdialog\") {",
    "      const dismissed = await dismissCommonDialogs(page);",
    "      return { action, ok: true, detail: dismissed ? \"dismissed dialog\" : \"no dialog\" };",
    "    }",
    "    if (action === \"fill\" || action === \"type\") {",
    "      const value = hydratedValue(command, input);",
    "      if (value === undefined) return { action, ok: false, detail: \"fill value missing\" };",
    "      const locator = await locatorFor(page, command);",
    "      if (!locator) return { action, ok: command.optional === true, detail: \"fill target not found\" };",
    "      await locator.fill(value);",
    "      return { action, ok: true, detail: `filled ${targetText(command) || \"field\"}` };",
    "    }",
    "    if (action === \"select\" || action === \"selectoption\") {",
    "      const value = hydratedValue(command, input);",
    "      const locator = await locatorFor(page, command);",
    "      if (!value || !locator) return { action, ok: command.optional === true, detail: \"select target/value not found\" };",
    "      await locator.selectOption(value);",
    "      return { action, ok: true, detail: `selected ${value}` };",
    "    }",
    "    if (action === \"waitforselector\") {",
    "      const selector = readString(command, \"selector\");",
    "      if (!selector) return { action, ok: false, detail: \"selector missing\" };",
    "      await page.locator(selector).first().waitFor();",
    "      return { action, ok: true, detail: selector };",
    "    }",
    "    if (action === \"waitfortext\") {",
    "      const text = readString(command, \"text\");",
    "      if (!text) return { action, ok: false, detail: \"text missing\" };",
    "      await page.getByText(text, { exact: false }).first().waitFor();",
    "      return { action, ok: true, detail: text };",
    "    }",
    "    if (action === \"click\") {",
    "      const locator = await locatorFor(page, command);",
    "      if (!locator) return { action, ok: command.optional === true, detail: \"click target not found\" };",
    "      await locator.click();",
    "      return { action, ok: true, detail: `clicked ${targetText(command) || \"target\"}` };",
    "    }",
    "  } catch (error) {",
    "    return { action, ok: command.optional === true, detail: error instanceof Error ? error.message : String(error) };",
    "  }",
    "  return undefined;",
    "}",
    "",
    "async function clickCommitCandidate(page: Page, candidates: Record<string, unknown>[]): Promise<Record<string, unknown>> {",
    "  for (const candidate of candidates) {",
    "    const locator = await locatorFor(page, candidate);",
    "    if (!locator) continue;",
    "    try {",
    "      await locator.click({ timeout: 8000 });",
    "      return { action: \"commit_click\", ok: true, detail: `clicked ${targetText(candidate) || \"commit candidate\"}`, candidate: sanitizedCandidate(candidate) };",
    "    } catch {",
    "      continue;",
    "    }",
    "  }",
    "  const fallbackTexts = [\"Confirm\", \"Submit\", \"Book\", \"Reserve\", \"Schedule\", \"Continue\", \"Reservar\", \"Confirmar\", \"Enviar\", \"Continuar\", \"Siguiente\", \"Finalizar\"];",
    "  for (const text of fallbackTexts) {",
    "    const locator = page.getByRole(\"button\", { name: new RegExp(text, \"i\") }).first();",
    "    if (await locator.count().catch(() => 0)) {",
    "      await locator.click({ timeout: 8000 });",
    "      return { action: \"commit_click\", ok: true, detail: `clicked fallback button ${text}`, candidate: { label: text } };",
    "    }",
    "  }",
    "  return { action: \"commit_click\", ok: false, detail: \"missing_requirements: no clickable commit candidate matched the prepared form\" };",
    "}",
    "",
    "async function locatorFor(page: Page, command: Record<string, unknown>): Promise<Locator | undefined> {",
    "  const selectors = [readString(command, \"selector\"), ...readStringArray(command.selectors)].filter((item): item is string => Boolean(item));",
    "  for (const selector of selectors) {",
    "    const locator = page.locator(selector).first();",
    "    if (await locator.count().catch(() => 0)) return locator;",
    "  }",
    "  const labels = [readString(command, \"label\"), ...readStringArray(command.labels), readString(command, \"field\")].filter((item): item is string => Boolean(item));",
    "  for (const label of labels) {",
    "    const locator = page.getByLabel(label, { exact: false }).first();",
    "    if (await locator.count().catch(() => 0)) return locator;",
    "  }",
    "  const placeholders = [readString(command, \"placeholder\"), ...readStringArray(command.placeholders)].filter((item): item is string => Boolean(item));",
    "  for (const placeholder of placeholders) {",
    "    const locator = page.getByPlaceholder(placeholder, { exact: false }).first();",
    "    if (await locator.count().catch(() => 0)) return locator;",
    "  }",
    "  const text = readString(command, \"text\") ?? readString(command, \"name\") ?? readString(command, \"label\");",
    "  if (text) {",
    "    const button = page.getByRole(\"button\", { name: new RegExp(escapeRegExp(text), \"i\") }).first();",
    "    if (await button.count().catch(() => 0)) return button;",
    "    const byText = page.getByText(text, { exact: false }).first();",
    "    if (await byText.count().catch(() => 0)) return byText;",
    "  }",
    "  return undefined;",
    "}",
    "",
    "async function captureArtifact(page: Page, input: Record<string, unknown>, phase: string): Promise<Record<string, unknown>> {",
    "  const buffer = await page.screenshot({ fullPage: false, type: \"png\" });",
    "  return {",
    "    filename: `${safeFilename(readString(input, \"proposalId\") ?? \"external-action\")}-${phase}.png`,",
    "    mimeType: \"image/png\",",
    "    contentBase64: buffer.toString(\"base64\"),",
    "    description: `${phase} proof for approved external action at ${page.url()}`,",
    "  };",
    "}",
    "",
    "async function saveArtifact(context: unknown, artifact: Record<string, unknown>): Promise<void> {",
    "  const writer = readRecord(readRecord(context)?.artifacts);",
    "  const saveGenerated = writer?.saveGenerated;",
    "  if (typeof saveGenerated === \"function\") {",
    "    await saveGenerated({",
    "      filename: readString(artifact, \"filename\") ?? \"external-action-proof.png\",",
    "      mimeType: readString(artifact, \"mimeType\") ?? \"image/png\",",
    "      content: Buffer.from(readString(artifact, \"contentBase64\") ?? \"\", \"base64\"),",
    "      description: readString(artifact, \"description\") ?? \"External action proof\",",
    "    });",
    "  }",
    "}",
    "",
    "function hydratedValue(command: Record<string, unknown>, input: Record<string, unknown>): string | undefined {",
    "  const direct = readString(command, \"value\") ?? readString(command, \"text\");",
    "  if (command.source !== \"approved_profile\") return direct;",
    "  const hydration = readRecord(input.hydratedInputs);",
    "  const fields = readRecords(hydration?.fields);",
    "  const wanted = [readString(command, \"field\"), readString(command, \"label\")].filter((item): item is string => Boolean(item)).map(normalizedKey);",
    "  const match = fields.find((field) => [readString(field, \"field\"), readString(field, \"label\")].some((value) => value && wanted.includes(normalizedKey(value))));",
    "  return readString(match, \"value\") ?? direct;",
    "}",
    "",
    "function browserLaunchOptions() {",
    "  const executablePath = resolveExecutablePath();",
    "  return {",
    "    headless: true,",
    "    executablePath,",
    "    args: [\"--no-sandbox\", \"--disable-dev-shm-usage\", \"--disable-setuid-sandbox\"],",
    "  };",
    "}",
    "",
    "function resolveExecutablePath(): string | undefined {",
    "  const env = process.env.CHROMIUM_PATH ?? process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;",
    "  if (env && existsSync(env)) return env;",
    "  const roots = [",
    "    join(homedir(), \"Library\", \"Caches\", \"ms-playwright\"),",
    "    join(homedir(), \".cache\", \"ms-playwright\"),",
    "    \"/ms-playwright\",",
    "  ];",
    "  for (const root of roots) {",
    "    if (!existsSync(root)) continue;",
    "    for (const entry of readdirSync(root)) {",
    "      const mac = join(root, entry, \"chrome-mac\", \"Chromium.app\", \"Contents\", \"MacOS\", \"Chromium\");",
    "      const linux = join(root, entry, \"chrome-linux\", \"chrome\");",
    "      if (existsSync(mac)) return mac;",
    "      if (existsSync(linux)) return linux;",
    "    }",
    "  }",
    "  return undefined;",
    "}",
    "",
    "async function dismissCommonDialogs(page: Page): Promise<boolean> {",
    "  const texts = [\"Accept\", \"Agree\", \"Allow all\", \"Reject\", \"OK\", \"Aceptar\", \"Acepto\", \"Rechazar\", \"Entendido\", \"Consent\"];",
    "  for (const text of texts) {",
    "    const locator = page.getByRole(\"button\", { name: new RegExp(escapeRegExp(text), \"i\") }).first();",
    "    if (await locator.count().catch(() => 0)) {",
    "      await locator.click({ timeout: 2000 }).catch(() => undefined);",
    "      return true;",
    "    }",
    "  }",
    "  return false;",
    "}",
    "",
    "function commandName(command: Record<string, unknown>): string {",
    "  return (readString(command, \"action\") ?? \"\").replace(/[^a-z]/gi, \"\").toLowerCase();",
    "}",
    "",
    "function targetText(command: Record<string, unknown>): string {",
    "  return [readString(command, \"text\"), readString(command, \"name\"), readString(command, \"label\"), readString(command, \"field\"), readString(command, \"selector\")].filter(Boolean).join(\" \");",
    "}",
    "",
    "function submittedPayloadSummary(input: Record<string, unknown>): string {",
    "  return summarizeValue({ proposedAction: input.proposedAction, payloadPreview: input.payloadPreview, target: input.target });",
    "}",
    "",
    "function inferConfirmationId(text: string): string | undefined {",
    "  return text.match(/(?:confirmation|booking|reservation|appointment|cita|reserva)\\s*(?:#|id|number|n[ºo.]*)?\\s*[:#]?\\s*([a-z0-9-]{4,})/i)?.[1];",
    "}",
    "",
    "function compactText(value: string, maxLength: number): string {",
    "  const text = value.replace(/\\s+/g, \" \").trim();",
    "  return text.length > maxLength ? `${text.slice(0, maxLength - 3)}...` : text;",
    "}",
    "",
    "function safeFilename(value: string): string {",
    "  return value.replace(/[^a-z0-9_.-]+/gi, \"-\").replace(/^-|-$/g, \"\").toLowerCase() || \"external-action\";",
    "}",
    "",
    "function escapeRegExp(value: string): string {",
    "  return value.replace(/[.*+?^${}()|[\\]\\\\]/g, \"\\\\$&\");",
    "}",
    "",
    "function sanitizedCandidate(candidate: Record<string, unknown>): Record<string, unknown> {",
    "  return { label: readString(candidate, \"label\") ?? readString(candidate, \"text\"), selector: readString(candidate, \"selector\"), reason: readString(candidate, \"reason\") };",
    "}",
    "",
    "function normalizedKey(value: string): string {",
    "  return value.toLowerCase().replace(/[^a-z0-9а-яё]+/gi, \"_\").replace(/^_+|_+$/g, \"\");",
    "}",
    "",
    "function readRecords(value: unknown): Record<string, unknown>[] {",
    "  return Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => Boolean(readRecord(item))) : [];",
    "}",
    "",
    "function blocked(reason: string, input: Record<string, unknown>, extra: Record<string, unknown>) {",
    "  return {",
    "    ok: false,",
    "    content: reason,",
    "    data: {",
    "      ...extra,",
    "      proposalId: readString(input, \"proposalId\"),",
    "      actionType: readString(input, \"actionType\"),",
    "      preparedUrl: readPreparedUrl(input),",
    "      replayStepCount: Array.isArray(input.replaySteps) ? input.replaySteps.length : 0,",
    "      sourceUrls: readStringArray(input.sourceUrls),",
    "      artifactIds: readStringArray(input.artifactIds),",
    "    },",
    "  };",
    "}",
    "",
    "function readFixtureConfirmation(input: Record<string, unknown>): { provider: string; confirmationId: string } | undefined {",
    "  const operatorInput = readRecord(input.operatorInput);",
    "  const confirmationId = readString(operatorInput, \"fixtureConfirmation\")",
    "    ?? readString(operatorInput, \"mockProviderConfirmation\")",
    "    ?? readString(operatorInput, \"confirmationId\");",
    "  if (!confirmationId) return undefined;",
    "  return { provider: readString(operatorInput, \"provider\") ?? \"fixture\", confirmationId };",
    "}",
    "",
    "function readPreparedUrl(input: Record<string, unknown>): string | undefined {",
    "  const preparedSession = readRecord(input.preparedSession);",
    "  return readString(preparedSession, \"currentUrl\") ?? readString(input, \"currentUrl\");",
    "}",
    "",
    "async function commitLocalFixtureIfAvailable(",
    "  input: Record<string, unknown>,",
    "  confirmation: { provider: string; confirmationId: string } | undefined,",
    "): Promise<{ ok: boolean; content: string; data?: Record<string, unknown> } | undefined> {",
    "  if (!confirmation) return undefined;",
    "  const preparedUrl = readPreparedUrl(input);",
    "  if (!preparedUrl || !/\\/api\\/fixtures\\/external-actions\\//.test(preparedUrl)) return undefined;",
    "  const commitUrl = `${preparedUrl.replace(/\\/+$/u, \"\")}/commit`;",
    "  const response = await fetch(commitUrl, {",
    "    method: \"POST\",",
    "    headers: { \"content-type\": \"application/json\" },",
    "    body: JSON.stringify({",
    "      fixtureConfirmation: confirmation.confirmationId,",
    "      proposalId: readString(input, \"proposalId\"),",
    "      actionType: readString(input, \"actionType\"),",
    "      proposedAction: input.proposedAction,",
    "      preparedSession: input.preparedSession,",
    "      replayStepCount: Array.isArray(input.replaySteps) ? input.replaySteps.length : 0,",
    "      artifactIds: readStringArray(input.artifactIds),",
    "    }),",
    "  });",
    "  const text = await response.text();",
    "  let data: Record<string, unknown> | undefined;",
    "  try {",
    "    const parsed = text ? JSON.parse(text) : undefined;",
    "    if (readRecord(parsed)) data = parsed as Record<string, unknown>;",
    "  } catch {",
    "    data = { raw: text };",
    "  }",
    "  if (!response.ok) {",
    "    return {",
    "      ok: false,",
    "      content: `fixture commit endpoint failed with HTTP ${response.status}` ,",
    "      data: { status: response.status, response: data ?? text },",
    "    };",
    "  }",
    "  return {",
    "    ok: true,",
    "    content: \"fixture commit endpoint accepted approved action\",",
    "    data: data ?? { provider: confirmation.provider, confirmationId: confirmation.confirmationId },",
    "  };",
    "}",
    "",
    "function readRecord(value: unknown): Record<string, unknown> | undefined {",
    "  return value && typeof value === \"object\" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;",
    "}",
    "",
    "function readString(record: Record<string, unknown> | undefined, key: string): string | undefined {",
    "  const value = record?.[key];",
    "  return typeof value === \"string\" && value.trim() ? value.trim() : undefined;",
    "}",
    "",
    "function readStringArray(value: unknown): string[] {",
    "  return Array.isArray(value) ? value.filter((item): item is string => typeof item === \"string\" && item.trim().length > 0) : [];",
    "}",
    "",
    "function summarizeValue(value: unknown): string {",
    "  try {",
    "    const json = JSON.stringify(value);",
    "    return json.length > 500 ? `${json.slice(0, 497)}...` : json;",
    "  } catch {",
    "    return String(value);",
    "  }",
    "}",
    "",
  ].join("\n");
}

export function renderExternalActionCommitToolTest(fileBase: string): string {
  return [
    "import test from \"node:test\";",
    "import assert from \"node:assert/strict\";",
    `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
    "",
    "test(\"external action commit executor blocks missing provider implementation\", async () => {",
    "  const result = await tool.run({ proposalId: \"proposal-1\", actionType: \"reservation\", proposedAction: { partySize: 2 } });",
    "  const data = result.data as Record<string, unknown> | undefined;",
    "  assert.equal(result.ok, false);",
    "  assert.match(result.content, /missing_requirements/);",
    "  assert.equal(data?.proposalId, \"proposal-1\");",
    "});",
    "",
    "test(\"external action commit executor accepts fixture confirmation\", async () => {",
    "  const result = await tool.run({",
    "    proposalId: \"proposal-1\",",
    "    actionType: \"reservation\",",
    "    proposedAction: { partySize: 2 },",
    "    preparedSession: { currentUrl: \"https://example.com/reserve\" },",
    "    artifactIds: [\"artifact-1\"],",
    "    operatorInput: { fixtureConfirmation: \"fixture-confirmed-1\" },",
    "  });",
    "  const data = result.data as Record<string, unknown> | undefined;",
    "  assert.equal(result.ok, true);",
    "  assert.equal(data?.confirmationId, \"fixture-confirmed-1\");",
    "  assert.equal(data?.preparedUrl, \"https://example.com/reserve\");",
    "});",
    "",
  ].join("\n");
}
