import type { ToolPackageManifest } from "./toolPackage.js";
import type { ToolCreationV1Result } from "./toolCreationV1.js";

export function renderWebSearchToolSource(
  input: ToolCreationV1Result["input"],
  manifest: Omit<ToolPackageManifest, "package">,
): string {
  return [
    "import type { Tool } from \"../tool.js\";",
    "",
    `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
    `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
    "",
    "type SearchResult = { title: string; url: string; snippet: string };",
    "",
    "export const tool: Tool = {",
    `  name: ${JSON.stringify(input.name)},`,
    `  displayName: ${JSON.stringify(input.displayName)},`,
    `  version: ${JSON.stringify(input.version)},`,
    `  description: ${JSON.stringify(input.description)},`,
    `  capabilities: ${JSON.stringify(input.capabilities)},`,
    `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
    "  inputSchema,",
    "  outputSchema,",
    "  async healthcheck() {",
    "    return { ok: true, detail: \"Web search tool loaded. Configure SEARCH_JSON_ENDPOINT for a provider endpoint, or use DuckDuckGo HTML fallback.\" };",
    "  },",
    "  async run(input) {",
    "    const query = typeof input.query === \"string\" ? input.query.trim() : \"\";",
    "    if (!query) return { ok: false, content: \"query is required\" };",
    "    const limit = clampInteger(input.limit, 5, 1, 10);",
    "    const endpoint = process.env.SEARCH_JSON_ENDPOINT || process.env.WEB_SEARCH_JSON_ENDPOINT;",
    "    const results = endpoint",
    "      ? await searchJsonEndpoint(endpoint, query, limit)",
    "      : await searchDuckDuckGoHtml(query, limit);",
    "    const enriched = await enrichResults(results, query, Math.min(limit, 5));",
    "    if (enriched.length === 0) {",
    "      return { ok: false, content: `No search results returned for ${query}`, data: { query, results: enriched } };",
    "    }",
    "    return {",
    "      ok: true,",
    "      content: enriched.map((result, index) => `${index + 1}. ${result.title}\\n${result.url}\\n${result.snippet}`).join(\"\\n\\n\"),",
    "      data: { query, results: enriched },",
    "    };",
    "  },",
    "};",
    "",
    "async function searchJsonEndpoint(endpoint: string, query: string, limit: number): Promise<SearchResult[]> {",
    "  const url = new URL(endpoint);",
    "  if (!url.searchParams.has(\"q\") && !url.searchParams.has(\"query\")) url.searchParams.set(\"q\", query);",
    "  if (!url.searchParams.has(\"format\") && /searx|search/i.test(url.hostname + url.pathname)) url.searchParams.set(\"format\", \"json\");",
    "  const response = await fetch(url, { headers: { accept: \"application/json\" } });",
    "  if (!response.ok) throw new Error(`Search endpoint failed with HTTP ${response.status}`);",
    "  const body = await response.json() as Record<string, unknown>;",
    "  const rawResults = Array.isArray(body.results) ? body.results : Array.isArray(body.items) ? body.items : [];",
    "  return rawResults.slice(0, limit).map(normalizeJsonResult).filter((item): item is SearchResult => Boolean(item));",
    "}",
    "",
    "async function enrichResults(results: SearchResult[], query: string, limit: number): Promise<SearchResult[]> {",
    "  const selected = results.slice(0, limit);",
    "  const enriched = await Promise.all(selected.map(async (result) => {",
    "    const preview = await fetchPagePreview(result.url, query).catch(() => undefined);",
    "    if (!preview) return result;",
    "    return {",
    "      ...result,",
    "      title: preview.title || result.title,",
    "      snippet: [result.snippet, preview.snippet].filter(Boolean).join(\" \").slice(0, 1200),",
    "    };",
    "  }));",
    "  return enriched;",
    "}",
    "",
    "async function fetchPagePreview(url: string, query: string): Promise<{ title?: string; snippet: string } | undefined> {",
    "  const controller = new AbortController();",
    "  const timeout = setTimeout(() => controller.abort(), 6000);",
    "  try {",
    "    const response = await fetch(url, {",
    "      signal: controller.signal,",
    "      headers: {",
    "        accept: \"text/html,application/xhtml+xml,text/plain;q=0.8\",",
    "        \"user-agent\": \"Mozilla/5.0 AgenticTool/0.1\",",
    "      },",
    "    });",
    "    const contentType = response.headers.get(\"content-type\") ?? \"\";",
    "    if (!response.ok || !/text\\/html|text\\/plain|application\\/xhtml/i.test(contentType)) return undefined;",
    "    const html = (await response.text()).slice(0, 250000);",
    "    return extractPagePreview(html, query);",
    "  } finally {",
    "    clearTimeout(timeout);",
    "  }",
    "}",
    "",
    "function extractPagePreview(html: string, query: string): { title?: string; snippet: string } | undefined {",
    "  const title = decodeHtml(stripTags(html.match(/<title[^>]*>([\\s\\S]*?)<\\/title>/i)?.[1] ?? \"\")).trim();",
    "  const meta = metaContent(html, \"description\") || metaContent(html, \"og:description\") || metaContent(html, \"twitter:description\");",
    "  const cleanText = stripTags(html",
    "    .replace(/<script[\\s\\S]*?<\\/script>/gi, \" \")",
    "    .replace(/<style[\\s\\S]*?<\\/style>/gi, \" \"))",
    "    .replace(/\\s+/g, \" \")",
    "    .trim();",
    "  const focused = focusSnippet(cleanText, query);",
    "  const snippet = [meta, focused].filter(Boolean).join(\" \").slice(0, 1200);",
    "  return title || snippet ? { title, snippet } : undefined;",
    "}",
    "",
    "function metaContent(html: string, name: string): string | undefined {",
    "  const escaped = name.replace(/[.*+?^${}()|[\\]\\\\]/g, \"\\\\$&\");",
    "  const pattern = new RegExp(`<meta[^>]+(?:name|property)=[\"']${escaped}[\"'][^>]+content=[\"']([^\"']+)[\"'][^>]*>`, \"i\");",
    "  const reversePattern = new RegExp(`<meta[^>]+content=[\"']([^\"']+)[\"'][^>]+(?:name|property)=[\"']${escaped}[\"'][^>]*>`, \"i\");",
    "  return decodeHtml(pattern.exec(html)?.[1] ?? reversePattern.exec(html)?.[1] ?? \"\").trim() || undefined;",
    "}",
    "",
    "function focusSnippet(text: string, query: string): string {",
    "  if (!text) return \"\";",
    "  const terms = query.toLowerCase().split(/[^a-z0-9а-яё$€£.,]+/iu).filter((term) => term.length >= 3);",
    "  const lower = text.toLowerCase();",
    "  const positions = terms.map((term) => lower.indexOf(term)).filter((index) => index >= 0);",
    "  const start = positions.length > 0 ? Math.max(0, Math.min(...positions) - 300) : 0;",
    "  return text.slice(start, start + 900);",
    "}",
    "",
    "async function searchDuckDuckGoHtml(query: string, limit: number): Promise<SearchResult[]> {",
    "  const url = new URL(\"https://duckduckgo.com/html/\");",
    "  url.searchParams.set(\"q\", query);",
    "  const response = await fetch(url, {",
    "    headers: {",
    "      accept: \"text/html,application/xhtml+xml\",",
    "      \"user-agent\": \"Mozilla/5.0 AgenticTool/0.1\",",
    "    },",
    "  });",
    "  if (!response.ok) throw new Error(`DuckDuckGo search failed with HTTP ${response.status}`);",
    "  const html = await response.text();",
    "  return parseDuckDuckGoHtml(html).slice(0, limit);",
    "}",
    "",
    "function normalizeJsonResult(value: unknown): SearchResult | undefined {",
    "  if (!value || typeof value !== \"object\" || Array.isArray(value)) return undefined;",
    "  const record = value as Record<string, unknown>;",
    "  const title = text(record.title ?? record.name);",
    "  const url = text(record.url ?? record.link);",
    "  const snippet = text(record.content ?? record.snippet ?? record.description ?? record.body) ?? \"\";",
    "  if (!title || !url) return undefined;",
    "  return { title, url, snippet };",
    "}",
    "",
    "function parseDuckDuckGoHtml(html: string): SearchResult[] {",
    "  const results: SearchResult[] = [];",
    "  const blocks = html.split(/<div[^>]+class=\"[^\"]*result[^\"]*\"/i).slice(1);",
    "  for (const block of blocks) {",
    "    const linkMatch = block.match(/<a[^>]+class=\"[^\"]*result__a[^\"]*\"[^>]+href=\"([^\"]+)\"[^>]*>([\\s\\S]*?)<\\/a>/i);",
    "    if (!linkMatch) continue;",
    "    const title = decodeHtml(stripTags(linkMatch[2] ?? \"\")).trim();",
    "    const rawUrl = decodeHtml(linkMatch[1] ?? \"\").trim();",
    "    const snippetMatch = block.match(/<a[^>]+class=\"[^\"]*result__snippet[^\"]*\"[^>]*>([\\s\\S]*?)<\\/a>|<div[^>]+class=\"[^\"]*result__snippet[^\"]*\"[^>]*>([\\s\\S]*?)<\\/div>/i);",
    "    const snippet = decodeHtml(stripTags(snippetMatch?.[1] ?? snippetMatch?.[2] ?? \"\")).trim();",
    "    const url = normalizeDuckDuckGoUrl(rawUrl);",
    "    if (title && url) results.push({ title, url, snippet });",
    "  }",
    "  return results;",
    "}",
    "",
    "function normalizeDuckDuckGoUrl(value: string): string {",
    "  try {",
    "    const parsed = new URL(value, \"https://duckduckgo.com\");",
    "    const uddg = parsed.searchParams.get(\"uddg\");",
    "    return uddg ? decodeURIComponent(uddg) : parsed.toString();",
    "  } catch {",
    "    return value;",
    "  }",
    "}",
    "",
    "function stripTags(value: string): string {",
    "  return value.replace(/<[^>]*>/g, \" \").replace(/\\s+/g, \" \");",
    "}",
    "",
    "function decodeHtml(value: string): string {",
    "  return value",
    "    .replace(/&amp;/g, \"&\")",
    "    .replace(/&quot;/g, \"\\\"\")",
    "    .replace(/&#39;/g, \"'\")",
    "    .replace(/&lt;/g, \"<\")",
    "    .replace(/&gt;/g, \">\")",
    "    .replace(/&#x([0-9a-f]+);/gi, (_match, hex) => String.fromCodePoint(Number.parseInt(hex, 16)))",
    "    .replace(/&#(\\d+);/g, (_match, decimal) => String.fromCodePoint(Number.parseInt(decimal, 10)));",
    "}",
    "",
    "function text(value: unknown): string | undefined {",
    "  return typeof value === \"string\" && value.trim() ? value.trim() : undefined;",
    "}",
    "",
    "function clampInteger(value: unknown, fallback: number, min: number, max: number): number {",
    "  const numberValue = typeof value === \"number\" && Number.isFinite(value) ? Math.floor(value) : fallback;",
    "  return Math.min(max, Math.max(min, numberValue));",
    "}",
    "",
  ].join("\n");
}

export function renderWebReadToolSource(
  input: ToolCreationV1Result["input"],
  manifest: Omit<ToolPackageManifest, "package">,
): string {
  return [
    "import type { Tool } from \"../tool.js\";",
    "",
    `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
    `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
    "",
    "type Link = { text: string; href: string };",
    "",
    "export const tool: Tool = {",
    `  name: ${JSON.stringify(input.name)},`,
    `  displayName: ${JSON.stringify(input.displayName)},`,
    `  version: ${JSON.stringify(input.version)},`,
    `  description: ${JSON.stringify(input.description)},`,
    `  capabilities: ${JSON.stringify(input.capabilities)},`,
    `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
    "  inputSchema,",
    "  outputSchema,",
    "  async healthcheck() {",
    "    return { ok: true, detail: \"Web read tool loaded. Fetches known URLs and extracts readable text/links.\" };",
    "  },",
    "  async run(input) {",
    "    const parsed = parseInput(input);",
    "    if (!parsed.ok) return { ok: false, content: parsed.error };",
    "    const controller = new AbortController();",
    "    const timeout = setTimeout(() => controller.abort(), parsed.timeoutMs);",
    "    try {",
    "      const response = await fetch(parsed.url, {",
    "        signal: controller.signal,",
    "        headers: {",
    "          accept: \"text/html,application/xhtml+xml,text/plain;q=0.8,application/json;q=0.5\",",
    "          \"user-agent\": \"Mozilla/5.0 AgenticTool/0.1 web.read\",",
    "        },",
    "      });",
    "      const contentType = response.headers.get(\"content-type\") ?? \"\";",
    "      const raw = await response.text();",
    "      const extracted = extractReadable(raw, response.url, contentType, parsed.focusText, parsed.maxLength);",
    "      const links = parsed.includeLinks ? extractLinks(raw, response.url).slice(0, 80) : [];",
    "      return {",
    "        ok: response.ok,",
    "        content: [extracted.title, response.url, extracted.text].filter(Boolean).join(\"\\n\\n\"),",
    "        data: {",
    "          url: response.url,",
    "          status: response.status,",
    "          statusText: response.statusText,",
    "          contentType,",
    "          title: extracted.title,",
    "          text: extracted.text,",
    "          textLength: extracted.text.length,",
    "          truncated: extracted.truncated,",
    "          focusText: parsed.focusText,",
    "          links,",
    "        },",
    "      };",
    "    } finally {",
    "      clearTimeout(timeout);",
    "    }",
    "  },",
    "};",
    "",
    "function parseInput(input: Record<string, unknown>):",
    "  | { ok: true; url: string; maxLength: number; focusText?: string; includeLinks: boolean; timeoutMs: number }",
    "  | { ok: false; error: string } {",
    "  const rawUrl = typeof input.url === \"string\" ? input.url.trim() : \"\";",
    "  if (!rawUrl) return { ok: false, error: \"url is required\" };",
    "  let url: URL;",
    "  try {",
    "    url = new URL(rawUrl);",
    "  } catch {",
    "    return { ok: false, error: \"url must be a valid URL\" };",
    "  }",
    "  if (url.protocol !== \"http:\" && url.protocol !== \"https:\") return { ok: false, error: \"url must use http or https\" };",
    "  return {",
    "    ok: true,",
    "    url: url.toString(),",
    "    maxLength: clampInteger(input.maxLength, 8000, 200, 50000),",
    "    focusText: typeof input.focusText === \"string\" && input.focusText.trim() ? input.focusText.trim().slice(0, 200) : undefined,",
    "    includeLinks: typeof input.includeLinks === \"boolean\" ? input.includeLinks : true,",
    "    timeoutMs: clampInteger(input.timeoutMs, 15000, 1000, 60000),",
    "  };",
    "}",
    "",
    "function extractReadable(raw: string, url: string, contentType: string, focusText: string | undefined, maxLength: number): { title?: string; text: string; truncated: boolean } {",
    "  if (/application\\/json/i.test(contentType)) {",
    "    const text = raw.replace(/\\s+/g, \" \").trim();",
    "    return trimFocused({ text, focusText, maxLength });",
    "  }",
    "  if (!/text\\/html|application\\/xhtml/i.test(contentType)) {",
    "    const text = raw.replace(/\\s+/g, \" \").trim();",
    "    return trimFocused({ text, focusText, maxLength });",
    "  }",
    "  const title = decodeHtml(stripTags(raw.match(/<title[^>]*>([\\s\\S]*?)<\\/title>/i)?.[1] ?? \"\")).trim() || undefined;",
    "  const html = raw",
    "    .replace(/<script[\\s\\S]*?<\\/script>/gi, \" \")",
    "    .replace(/<style[\\s\\S]*?<\\/style>/gi, \" \")",
    "    .replace(/<noscript[\\s\\S]*?<\\/noscript>/gi, \" \");",
    "  const main = firstMatch(html, /<main[^>]*>([\\s\\S]*?)<\\/main>/i)",
    "    ?? firstMatch(html, /<article[^>]*>([\\s\\S]*?)<\\/article>/i)",
    "    ?? html;",
    "  const text = decodeHtml(stripTags(main)).replace(/\\s+/g, \" \").trim();",
    "  return { title, ...trimFocused({ text, focusText, maxLength }) };",
    "}",
    "",
    "function trimFocused(input: { text: string; focusText?: string; maxLength: number }): { text: string; truncated: boolean } {",
    "  const { text, focusText, maxLength } = input;",
    "  if (text.length <= maxLength) return { text, truncated: false };",
    "  const lower = text.toLowerCase();",
    "  const focus = focusText?.toLowerCase();",
    "  const index = focus ? lower.indexOf(focus) : -1;",
    "  const start = index >= 0 ? Math.max(0, index - Math.floor(maxLength / 3)) : 0;",
    "  return { text: text.slice(start, start + maxLength), truncated: true };",
    "}",
    "",
    "function extractLinks(raw: string, baseUrl: string): Link[] {",
    "  const links: Link[] = [];",
    "  for (const match of raw.matchAll(/<a\\s+[^>]*href=[\"']([^\"']+)[\"'][^>]*>([\\s\\S]*?)<\\/a>/gi)) {",
    "    const href = resolveUrl(match[1] ?? \"\", baseUrl);",
    "    const text = decodeHtml(stripTags(match[2] ?? \"\")).replace(/\\s+/g, \" \").trim();",
    "    if (href) links.push({ href, text: text.slice(0, 160) });",
    "  }",
    "  return links;",
    "}",
    "",
    "function firstMatch(text: string, pattern: RegExp): string | undefined {",
    "  return pattern.exec(text)?.[1];",
    "}",
    "",
    "function resolveUrl(value: string, baseUrl: string): string | undefined {",
    "  try {",
    "    const url = new URL(decodeHtml(value), baseUrl);",
    "    return url.protocol === \"http:\" || url.protocol === \"https:\" ? url.toString() : undefined;",
    "  } catch {",
    "    return undefined;",
    "  }",
    "}",
    "",
    "function stripTags(value: string): string {",
    "  return value.replace(/<[^>]*>/g, \" \");",
    "}",
    "",
    "function decodeHtml(value: string): string {",
    "  return value",
    "    .replace(/&amp;/g, \"&\")",
    "    .replace(/&quot;/g, \"\\\"\")",
    "    .replace(/&#39;/g, \"'\")",
    "    .replace(/&lt;/g, \"<\")",
    "    .replace(/&gt;/g, \">\")",
    "    .replace(/&#x([0-9a-f]+);/gi, (_match, hex) => String.fromCodePoint(Number.parseInt(hex, 16)))",
    "    .replace(/&#(\\d+);/g, (_match, decimal) => String.fromCodePoint(Number.parseInt(decimal, 10)));",
    "}",
    "",
    "function clampInteger(value: unknown, fallback: number, min: number, max: number): number {",
    "  const numberValue = typeof value === \"number\" && Number.isFinite(value) ? Math.floor(value) : fallback;",
    "  return Math.min(max, Math.max(min, numberValue));",
    "}",
    "",
  ].join("\n");
}

