import type { ToolCreationV1Result } from "./toolCreationV1.js";
import type { ToolPackageManifest } from "./toolPackage.js";

export function renderHttpJsonToolSource(
  input: ToolCreationV1Result["input"],
  manifest: Omit<ToolPackageManifest, "package">,
): string {
  return [
    "import type { Tool } from \"../tool.js\";",
    "",
    `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
    `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
    `const integration = ${JSON.stringify(input.integrationContract, null, 2)} as any;`,
    "",
    "export const tool: Tool = {",
    `  name: ${JSON.stringify(input.name)},`,
    `  displayName: ${JSON.stringify(input.displayName)},`,
    `  version: ${JSON.stringify(input.version)},`,
    `  description: ${JSON.stringify(input.description)},`,
    `  capabilities: ${JSON.stringify(input.capabilities)},`,
    `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
    "  inputSchema,",
    "  outputSchema,",
    "  async healthcheck() {",
    "    return { ok: true, detail: integration ? `HTTP API client loaded (${integration.operations?.length ?? 0} operation contract(s)).` : \"HTTP API client loaded.\" };",
    "  },",
    "  async run(input, context) {",
    "    const request = buildRequest(input, context);",
    "    if (!request.ok) return { ok: false, content: request.error, data: { diagnostic: request.diagnostic } };",
    "    const maxLength = typeof input.maxLength === \"number\" && Number.isFinite(input.maxLength)",
    "      ? Math.max(1, Math.min(20000, Math.floor(input.maxLength)))",
    "      : 4000;",
    "    const timeoutMs = parseFetchTimeoutMs(input.timeoutMs);",
    "    const startedAt = Date.now();",
    "    let response: Response;",
    "    try {",
    "      response = await fetchWithTimeout(request.url, request.init, timeoutMs);",
    "    } catch (error) {",
    "      const timedOut = isAbortLikeError(error);",
    "      return {",
    "        ok: false,",
    "        content: timedOut",
    "          ? `HTTP API request timed out after ${timeoutMs} ms before a response was received.`",
    "          : `HTTP API request failed before a response was received: ${errorMessage(error)}` ,",
    "        data: {",
    "          diagnostic: timedOut ? \"http_request_timeout\" : \"http_request_failed\",",
    "          request: request.diagnostic,",
    "          durationMs: Date.now() - startedAt,",
    "          error: { name: errorName(error), message: errorMessage(error) },",
    "        },",
    "      };",
    "    }",
    "    const text = await response.text();",
    "    const contentType = response.headers.get(\"content-type\");",
    "    const parsed = parseResponseBody(text, contentType);",
    "    const baseData = {",
    "      response: {",
    "        url: redactUrl(response.url),",
    "        status: response.status,",
    "        statusText: response.statusText,",
    "        contentType,",
    "        truncated: text.length > maxLength,",
    "        operationId: request.operationId,",
    "        method: request.method,",
    "        target: request.target,",
    "        targetBaseUrl: request.targetBaseUrl,",
    "      },",
    "      request: request.diagnostic,",
    "    };",
    "    if (looksLikeHtmlApiMismatch(text, contentType)) {",
    "      return {",
    "        ok: false,",
    "        content: `HTTP API request returned HTML instead of a machine-readable API response (${response.status} ${response.statusText}).`,",
    "        data: { value: text.slice(0, maxLength), ...baseData, diagnostic: \"html_api_mismatch\" },",
    "      };",
    "    }",
    "    const data = parsed && typeof parsed === \"object\" && !Array.isArray(parsed)",
    "      ? { ...(parsed as Record<string, unknown>), ...baseData }",
    "      : { value: parsed ?? text, ...baseData };",
    "    if (!response.ok) {",
    "      const providerError = normalizeProviderError(parsed, text, response.status, response.statusText, request.diagnostic);",
    "      return {",
    "        ok: false,",
    "        content: `HTTP API provider returned ${response.status} ${response.statusText}: ${providerError.summary}`.trim(),",
    "        data: { ...data, diagnostic: \"http_provider_error\", providerError },",
    "      };",
    "    }",
    "    return {",
    "      ok: true,",
    "      content: text.slice(0, maxLength),",
    "      data,",
    "    };",
    "  },",
    "};",
    "",
    "function buildRequest(input: Record<string, unknown>, context: unknown): { ok: true; url: URL; init: RequestInit; method: string; operationId?: string; target?: string; targetBaseUrl?: string; diagnostic: Record<string, unknown> } | { ok: false; error: string; diagnostic: Record<string, unknown> } {",
    "  const operationId = typeof input.operationId === \"string\" ? input.operationId : undefined;",
    "  const operations = Array.isArray(integration?.operations) ? integration.operations : [];",
    "  if (operationId && !findOperation(operationId)) return { ok: false, error: `unknown operationId: ${operationId}`, diagnostic: operationSelectionDiagnostic(input, operationId, operations) };",
    "  const operation = operationId ? findOperation(operationId) : inferOperationFromInput(input, operations);",
    "  const rawUrl = typeof input.url === \"string\" ? input.url.trim() : \"\";",
    "  const target = resolveTarget(input.target);",
    "  if (!target.ok) return target;",
    "  const rawBaseUrl = typeof input.baseUrl === \"string\" && input.baseUrl.trim()",
    "    ? input.baseUrl.trim()",
    "    : target.target?.baseUrl ?? (typeof integration?.baseUrl === \"string\" ? integration.baseUrl.trim() : \"\");",
    "  const operationPath = typeof operation?.path === \"string\" ? operation.path : \"\";",
    "  const rawPath = typeof input.path === \"string\" ? input.path.trim() : operationPath;",
    "  const requestedTarget = typeof input.target === \"string\" ? input.target.trim() : undefined;",
    "  if (!rawUrl && !operation && operations.length > 1) return { ok: false, error: \"operationId or an unambiguous path/pathParams input is required\", diagnostic: operationSelectionDiagnostic(input, operationId, operations) };",
    "  if (!rawUrl && (!rawBaseUrl || !rawPath)) return { ok: false, error: \"url or baseUrl+path is required\", diagnostic: requestDiagnostic({ operationId, operation, requestedTarget, target: target.target }) };",
    "  const path = applyPathParams(rawPath, input.pathParams);",
    "  if (!path.ok) return { ...path, diagnostic: requestDiagnostic({ operationId, operation, requestedTarget, target: target.target, rawBaseUrl, rawPath }) };",
    "  let url: URL;",
    "  try {",
    "    url = rawUrl ? new URL(rawUrl) : new URL(path.value.replace(/^\\/+/, \"\"), rawBaseUrl.endsWith(\"/\") ? rawBaseUrl : `${rawBaseUrl}/`);",
    "  } catch {",
    "    return { ok: false, error: \"url must be a valid HTTP or HTTPS URL\", diagnostic: requestDiagnostic({ operationId, operation, requestedTarget, target: target.target, rawBaseUrl, rawPath }) };",
    "  }",
    "  if (url.protocol !== \"http:\" && url.protocol !== \"https:\") return { ok: false, error: \"url must use http or https\", diagnostic: requestDiagnostic({ operationId, operation, requestedTarget, target: target.target, url }) };",
    "  const query = input.query && typeof input.query === \"object\" && !Array.isArray(input.query) ? input.query as Record<string, unknown> : {};",
    "  for (const [key, value] of Object.entries(query)) {",
    "    if (value === undefined || value === null) continue;",
    "    url.searchParams.set(key, String(value));",
    "  }",
    "  const method = parseMethod(input.method ?? operation?.method);",
    "  const headers = new Headers({ accept: \"application/json, text/plain;q=0.9, */*;q=0.8\" });",
    "  const rawHeaders = input.headers && typeof input.headers === \"object\" && !Array.isArray(input.headers) ? input.headers as Record<string, unknown> : {};",
    "  for (const [key, value] of Object.entries(rawHeaders)) {",
    "    if (typeof value === \"string\" && !isSecretLikeHeader(key)) headers.set(key, value);",
    "  }",
    "  const auth = applyIntegrationAuth(headers, url, context);",
    "  if (!auth.ok) return { ...auth, diagnostic: requestDiagnostic({ operationId, operation, requestedTarget, target: target.target, url, method, authMissing: true }) };",
    "  const body = input.body;",
    "  const init: RequestInit = { method, headers };",
    "  if (method !== \"GET\" && body !== undefined) {",
    "    headers.set(\"content-type\", \"application/json\");",
    "    init.body = typeof body === \"string\" ? body : JSON.stringify(body);",
    "  }",
    "  return {",
    "    ok: true,",
    "    url,",
    "    init,",
    "    method,",
    "    operationId: operationId ?? (typeof operation?.name === \"string\" ? operation.name : undefined),",
    "    target: target.target?.id,",
    "    targetBaseUrl: target.target?.baseUrl,",
    "    diagnostic: requestDiagnostic({ operationId, operation, requestedTarget, target: target.target, url, method }),",
    "  };",
    "}",
    "",
    "function requestDiagnostic(input: { operationId?: string; operation?: any; requestedTarget?: string; target?: any; rawBaseUrl?: string; rawPath?: string; url?: URL; method?: string; authMissing?: boolean }): Record<string, unknown> {",
    "  const auth = integration?.auth;",
    "  const requiredSecretHandle = Array.isArray(auth?.requiredSecretHandles) ? auth.requiredSecretHandles[0] : undefined;",
    "  return compact({",
    "    operationId: input.operationId ?? (typeof input.operation?.name === \"string\" ? input.operation.name : undefined),",
    "    method: input.method ?? parseMethod(input.operation?.method),",
    "    path: input.rawPath ?? (typeof input.operation?.path === \"string\" ? input.operation.path : undefined),",
    "    targetRequested: input.requestedTarget,",
    "    target: input.target?.id,",
    "    targetBaseUrl: input.target?.baseUrl ?? input.rawBaseUrl,",
    "    url: input.url ? redactUrl(input.url.toString()) : undefined,",
    "    auth: auth ? compact({ type: auth.type, credentialLocation: auth.credentialLocation, credentialName: auth.credentialName, requiredSecretHandle, missing: input.authMissing || undefined }) : undefined,",
    "    inputContract: operationInputContract(input.operation),",
    "  });",
    "}",
    "",
    "function operationInputContract(operation: any): Record<string, unknown> | undefined {",
    "  if (!operation) return undefined;",
    "  const schema = operation.inputSchema && typeof operation.inputSchema === \"object\" && !Array.isArray(operation.inputSchema) ? operation.inputSchema : undefined;",
    "  const properties = schema?.properties && typeof schema.properties === \"object\" && !Array.isArray(schema.properties) ? schema.properties as Record<string, unknown> : {};",
    "  return compact({",
    "    operationId: typeof operation.name === \"string\" ? operation.name : undefined,",
    "    method: parseMethod(operation.method),",
    "    path: typeof operation.path === \"string\" ? operation.path : undefined,",
    "    required: Array.isArray(schema?.required) ? schema.required : undefined,",
    "    pathParams: schemaKeys(properties.pathParams),",
    "    query: schemaKeys(properties.query),",
    "    body: schemaKeys(properties.body),",
    "  });",
    "}",
    "",
    "function operationSelectionDiagnostic(input: Record<string, unknown>, operationId: string | undefined, operations: any[]): Record<string, unknown> {",
    "  return compact({",
    "    operationId,",
    "    targetRequested: typeof input.target === \"string\" ? input.target.trim() : undefined,",
    "    availableOperations: operations.map((operation: any) => operationInputContract(operation)).filter(Boolean),",
    "  });",
    "}",
    "",
    "function schemaKeys(value: unknown): string[] | undefined {",
    "  const record = value && typeof value === \"object\" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;",
    "  const properties = record?.properties && typeof record.properties === \"object\" && !Array.isArray(record.properties) ? record.properties as Record<string, unknown> : undefined;",
    "  const keys = properties ? Object.keys(properties) : [];",
    "  return keys.length > 0 ? keys : undefined;",
    "}",
    "",
    "function findOperation(operationId: string): any | undefined {",
    "  const operations = Array.isArray(integration?.operations) ? integration.operations : [];",
    "  return operations.find((operation: any) => operation?.name === operationId);",
    "}",
    "",
    "function inferOperationFromInput(input: Record<string, unknown>, operations: any[]): any | undefined {",
    "  if (operations.length === 1) return operations[0];",
    "  const explicitPath = typeof input.path === \"string\" ? input.path.trim() : \"\";",
    "  if (explicitPath) {",
    "    const exact = operations.find((operation: any) => typeof operation?.path === \"string\" && operation.path === explicitPath);",
    "    if (exact) return exact;",
    "  }",
    "  const pathParams = input.pathParams && typeof input.pathParams === \"object\" && !Array.isArray(input.pathParams)",
    "    ? input.pathParams as Record<string, unknown>",
    "    : {};",
    "  const paramKeys = Object.keys(pathParams).filter((key) => pathParams[key] !== undefined && pathParams[key] !== null).sort();",
    "  if (paramKeys.length === 0) return undefined;",
    "  const normalizedParamKeys = paramKeys.map(normalizeFieldName);",
    "  const scored = operations.map((operation: any) => {",
    "    const path = typeof operation?.path === \"string\" ? operation.path : \"\";",
    "    const placeholders = [...path.matchAll(/\\{([^}]+)\\}|:([A-Za-z0-9_]+)/g)]",
    "      .map((match) => match[1] ?? match[2])",
    "      .filter((key): key is string => typeof key === \"string\")",
    "      .sort();",
    "    if (placeholders.length !== paramKeys.length) return { operation, score: -1 };",
    "    const exact = placeholders.every((key, index) => key === paramKeys[index]);",
    "    const normalized = placeholders.map(normalizeFieldName).every((key, index) => key === normalizedParamKeys[index]);",
    "    if (!exact && !normalized) return { operation, score: -1 };",
    "    return { operation, score: (exact ? 50 : 30) + queryCompatibilityScore(input.query, operation) };",
    "  }).filter((entry: { operation: any; score: number }) => entry.score >= 0)",
    "    .sort((left: { score: number }, right: { score: number }) => right.score - left.score);",
    "  if (scored.length === 0) return undefined;",
    "  if (scored.length === 1 || scored[0].score > scored[1].score) return scored[0].operation;",
    "  return undefined;",
    "}",
    "",
    "function queryCompatibilityScore(query: unknown, operation: any): number {",
    "  const inputKeys = query && typeof query === \"object\" && !Array.isArray(query) ? Object.keys(query as Record<string, unknown>) : [];",
    "  if (inputKeys.length === 0) return 0;",
    "  const querySchema = operation?.inputSchema?.properties?.query;",
    "  const properties = querySchema && typeof querySchema === \"object\" && !Array.isArray(querySchema)",
    "    ? (querySchema as { properties?: unknown }).properties",
    "    : undefined;",
    "  const allowedKeys = properties && typeof properties === \"object\" && !Array.isArray(properties)",
    "    ? Object.keys(properties as Record<string, unknown>)",
    "    : [];",
    "  const normalizedAllowed = new Set(allowedKeys.map(normalizeFieldName));",
    "  return inputKeys.reduce((score, key) => score + (normalizedAllowed.has(normalizeFieldName(key)) ? 10 : 0), 0);",
    "}",
    "",
    "function normalizeFieldName(value: string): string {",
    "  return value.replace(/[^A-Za-z0-9]/g, \"\").toLowerCase();",
    "}",
    "",
    "function resolveTarget(value: unknown): { ok: true; target?: any } | { ok: false; error: string; diagnostic: Record<string, unknown> } {",
    "  const requested = typeof value === \"string\" ? value.trim().toLowerCase() : \"\";",
    "  if (!requested) return { ok: true };",
    "  const targets = Array.isArray(integration?.targets) ? integration.targets : [];",
    "  const target = targets.find((candidate: any) => {",
    "    const ids = [candidate?.id, candidate?.label, ...(Array.isArray(candidate?.aliases) ? candidate.aliases : [])];",
    "    return ids.some((id) => typeof id === \"string\" && id.trim().toLowerCase() === requested);",
    "  });",
    "  if (target?.baseUrl && typeof target.baseUrl === \"string\") return { ok: true, target };",
    "  const available = targets.map((candidate: any) => candidate?.id).filter(Boolean).join(\", \");",
    "  return {",
    "    ok: false,",
    "    error: available ? `unknown target: ${requested}. available targets: ${available}` : `unknown target: ${requested}`,",
    "    diagnostic: {",
    "      targetRequested: requested,",
    "      availableTargets: targets.map((candidate: any) => compact({ id: candidate?.id, label: candidate?.label, aliases: Array.isArray(candidate?.aliases) ? candidate.aliases : undefined, baseUrl: candidate?.baseUrl })),",
    "    },",
    "  };",
    "}",
    "",
    "function applyPathParams(path: string, value: unknown): { ok: true; value: string } | { ok: false; error: string } {",
    "  const params = value && typeof value === \"object\" && !Array.isArray(value) ? value as Record<string, unknown> : {};",
    "  const replaced = path.replace(/\\{([^}]+)\\}|:([A-Za-z0-9_]+)/g, (match, braced: string | undefined, colon: string | undefined) => {",
    "    const key = braced ?? colon;",
    "    const raw = key ? params[key] : undefined;",
    "    return raw === undefined || raw === null ? match : encodeURIComponent(String(raw));",
    "  });",
    "  const missing = [...replaced.matchAll(/\\{([^}]+)\\}|:([A-Za-z0-9_]+)/g)].map((match) => match[1] ?? match[2]);",
    "  if (missing.length) return { ok: false, error: `missing path parameter(s): ${missing.join(\", \")}` };",
    "  return { ok: true, value: replaced };",
    "}",
    "",
    "function applyIntegrationAuth(headers: Headers, url: URL, context: unknown): { ok: true } | { ok: false; error: string } {",
    "  const auth = integration?.auth;",
    "  if (!auth || auth.type === \"none\") return { ok: true };",
    "  const handle = Array.isArray(auth.requiredSecretHandles) ? auth.requiredSecretHandles[0] : undefined;",
    "  if (!handle) return { ok: true };",
    "  const secret = resolveSecretFromContext(context, handle);",
    "  if (!secret) return { ok: false, error: `missing required secret handle: ${handle}` };",
    "  if (auth.type === \"api-key\") {",
    "    const name = typeof auth.credentialName === \"string\" && auth.credentialName ? auth.credentialName : \"x-api-key\";",
    "    if (auth.credentialLocation === \"query\") url.searchParams.set(name, secret);",
    "    else headers.set(name, secret);",
    "    return { ok: true };",
    "  }",
    "  if (auth.type === \"bearer-token\" || auth.type === \"oauth2\" || auth.type === \"bot-token\") {",
    "    const scheme = typeof auth.authorizationScheme === \"string\" && auth.authorizationScheme ? auth.authorizationScheme : \"Bearer\";",
    "    headers.set(\"authorization\", `${scheme} ${secret}`);",
    "    return { ok: true };",
    "  }",
    "  if (auth.type === \"basic\") {",
    "    headers.set(\"authorization\", `${typeof auth.authorizationScheme === \"string\" ? auth.authorizationScheme : \"Basic\"} ${secret}`);",
    "    return { ok: true };",
    "  }",
    "  return { ok: true };",
    "}",
    "",
    "function resolveSecretFromContext(context: unknown, handle: string): string | undefined {",
    "  if (!context || typeof context !== \"object\" || Array.isArray(context)) return undefined;",
    "  const secrets = (context as { secrets?: unknown }).secrets;",
    "  if (!secrets || typeof secrets !== \"object\" || Array.isArray(secrets)) return undefined;",
    "  const value = (secrets as Record<string, unknown>)[handle];",
    "  return typeof value === \"string\" && value.length > 0 ? value : undefined;",
    "}",
    "",
    "function parseMethod(value: unknown): string {",
    "  const method = typeof value === \"string\" ? value.toUpperCase() : \"GET\";",
    "  return [\"GET\", \"POST\", \"PUT\", \"PATCH\", \"DELETE\"].includes(method) ? method : \"GET\";",
    "}",
    "",
    "function parseResponseBody(text: string, contentType: string | null): unknown {",
    "  if (/json/i.test(contentType ?? \"\") || /^[\\s\\r\\n]*[{[]/.test(text)) {",
    "    try {",
    "      return JSON.parse(text);",
    "    } catch {",
    "      return text;",
    "    }",
    "  }",
    "  return text;",
    "}",
    "",
    "function normalizeProviderError(parsed: unknown, rawText: string, status: number, statusText: string, request: Record<string, unknown>): Record<string, unknown> {",
    "  const extracted = extractErrorFields(parsed);",
    "  const summary = firstUsefulString(extracted.message, extracted.error, extracted.detail, extracted.title, extracted.description, extracted.reason, rawText.slice(0, 500)) || \"Provider returned an error without a readable message.\";",
    "  return compact({",
    "    status,",
    "    statusText,",
    "    summary,",
    "    code: firstUsefulString(extracted.code, extracted.errorCode, extracted.statusCode),",
    "    category: classifyProviderError(status),",
    "    hints: providerErrorHints(status, request),",
    "    fields: compact(extracted),",
    "  });",
    "}",
    "",
    "function extractErrorFields(value: unknown): Record<string, unknown> {",
    "  if (typeof value === \"string\") return { message: value.slice(0, 500) };",
    "  if (Array.isArray(value)) return { message: value.slice(0, 3).map((entry) => firstUsefulString(extractErrorFields(entry).message, entry)).filter(Boolean).join(\"; \") };",
    "  const record = value && typeof value === \"object\" ? value as Record<string, unknown> : {};",
    "  const nested = firstObject(record.error, record.errors, record.detail, record.details, record.message, record.data);",
    "  const deeper = firstObject(nested?.error, nested?.errors, nested?.detail, nested?.details, nested?.message, nested?.data);",
    "  return compact({",
    "    message: firstUsefulString(record.message, record.errorMessage, nested?.message, deeper?.message),",
    "    error: firstUsefulString(record.error, nested?.error, deeper?.error),",
    "    detail: firstUsefulString(record.detail, nested?.detail, deeper?.detail),",
    "    title: firstUsefulString(record.title, nested?.title, deeper?.title),",
    "    description: firstUsefulString(record.description, record.error_description, nested?.description, deeper?.description),",
    "    reason: firstUsefulString(record.reason, nested?.reason, deeper?.reason),",
    "    code: firstUsefulString(record.code, nested?.code, deeper?.code),",
    "    errorCode: firstUsefulString(record.errorCode, record.error_code, nested?.errorCode, nested?.error_code, deeper?.errorCode, deeper?.error_code),",
    "    statusCode: firstUsefulString(record.statusCode, record.status_code, nested?.statusCode, nested?.status_code, deeper?.statusCode, deeper?.status_code),",
    "  });",
    "}",
    "",
    "function firstObject(...values: unknown[]): Record<string, unknown> | undefined {",
    "  for (const value of values) {",
    "    if (value && typeof value === \"object\" && !Array.isArray(value)) return value as Record<string, unknown>;",
    "    if (Array.isArray(value)) {",
    "      const nested = value.find((entry) => entry && typeof entry === \"object\" && !Array.isArray(entry));",
    "      if (nested) return nested as Record<string, unknown>;",
    "    }",
    "  }",
    "  return undefined;",
    "}",
    "",
    "function firstUsefulString(...values: unknown[]): string | undefined {",
    "  for (const value of values) {",
    "    if (typeof value === \"string\" && value.trim()) return value.trim().slice(0, 500);",
    "    if (typeof value === \"number\" || typeof value === \"boolean\") return String(value);",
    "  }",
    "  return undefined;",
    "}",
    "",
    "function classifyProviderError(status: number): string {",
    "  if (status === 401 || status === 403) return \"auth_or_permission\";",
    "  if (status === 404) return \"not_found_or_wrong_target\";",
    "  if (status === 408 || status === 429) return \"retryable_or_rate_limited\";",
    "  if (status === 400 || status === 422) return \"input_rejected\";",
    "  if (status >= 500) return \"provider_server_error\";",
    "  return \"http_error\";",
    "}",
    "",
    "function providerErrorHints(status: number, request: Record<string, unknown>): string[] {",
    "  const hints = [];",
    "  if (status === 401 || status === 403) hints.push(\"Check the required credential secret handle and provider permissions.\");",
    "  if (status === 400 || status === 422) hints.push(\"Check path/query/body parameters against request.inputContract before retrying.\");",
    "  if (status === 404) hints.push(\"Check selected target, base URL, operation path, and path parameters.\");",
    "  if (status === 408 || status === 429 || status >= 500) hints.push(\"Retry only after validating inputs; provider may be rate-limited, unavailable, or rejecting this parameter combination.\");",
    "  if (request.inputContract) hints.push(\"Use request.inputContract as the authoritative generated contract for the next attempt.\");",
    "  return hints;",
    "}",
    "",
    "function looksLikeHtmlApiMismatch(text: string, contentType: string | null): boolean {",
    "  const lowerType = (contentType ?? \"\").toLowerCase();",
    "  if (!/text\\/html|application\\/xhtml/.test(lowerType)) return false;",
    "  const lower = text.slice(0, 2000).toLowerCase();",
    "  return /<html|<!doctype html|<div id=[\"']app[\"']|enable javascript|<script\\b/.test(lower);",
    "}",
    "",
    "function isSecretLikeHeader(name: string): boolean {",
    "  return /authorization|api[-_]?key|token|secret|cookie/i.test(name);",
    "}",
    "",
    "function parseFetchTimeoutMs(value: unknown): number {",
    "  if (typeof value === \"number\" && Number.isFinite(value)) return Math.max(1000, Math.min(55000, Math.floor(value)));",
    "  return 50000;",
    "}",
    "",
    "async function fetchWithTimeout(url: URL, init: RequestInit, timeoutMs: number): Promise<Response> {",
    "  const controller = new AbortController();",
    "  const timeout = setTimeout(() => controller.abort(), timeoutMs);",
    "  try {",
    "    return await fetch(url, { ...init, signal: controller.signal });",
    "  } finally {",
    "    clearTimeout(timeout);",
    "  }",
    "}",
    "",
    "function isAbortLikeError(error: unknown): boolean {",
    "  return errorName(error) === \"AbortError\" || /aborted|abort|timeout/i.test(errorMessage(error));",
    "}",
    "",
    "function errorName(error: unknown): string {",
    "  return error && typeof error === \"object\" && typeof (error as { name?: unknown }).name === \"string\" ? (error as { name: string }).name : \"Error\";",
    "}",
    "",
    "function errorMessage(error: unknown): string {",
    "  return error instanceof Error ? error.message : String(error ?? \"unknown error\");",
    "}",
    "",
    "function redactUrl(value: string): string {",
    "  try {",
    "    const url = new URL(value);",
    "    for (const key of [...url.searchParams.keys()]) {",
    "      if (isSecretLikeHeader(key)) url.searchParams.set(key, \"[redacted]\");",
    "    }",
    "    if (url.username) url.username = \"[redacted]\";",
    "    if (url.password) url.password = \"[redacted]\";",
    "    return url.toString();",
    "  } catch {",
    "    return value.replace(/([?&][^=]*(?:token|secret|api[-_]?key|authorization)[^=]*=)[^&\\s]+/gi, \"$1[redacted]\");",
    "  }",
    "}",
    "",
    "function compact(input: Record<string, unknown>): Record<string, unknown> {",
    "  return Object.fromEntries(Object.entries(input).filter(([, value]) => value !== undefined));",
    "}",
    "",
  ].join("\n");
}
