import type { ToolCreationV1Result } from "./toolCreationV1.js";
import type { ToolPackageManifest } from "./toolPackage.js";
import { renderBrowserOperateToolSource } from "./toolCreationV1BrowserOperateRenderer.js";
import { renderBrowserScreenshotToolSource } from "./toolCreationV1BrowserRenderer.js";
import { renderExternalActionCommitToolSource, renderExternalActionCommitToolTest } from "./toolCreationV1ExternalActionCommitRenderer.js";
import { renderHttpJsonToolSource } from "./toolCreationV1HttpJsonSource.js";
import { telegramFormattingSourceLines } from "./toolCreationV1TelegramFormatting.js";
import { renderWebReadToolSource, renderWebSearchToolSource } from "./toolCreationV1WebRenderers.js";

export function renderToolSource(input: ToolCreationV1Result["input"], manifest: Omit<ToolPackageManifest, "package">): string {
  if (input.kind === "browser-screenshot") {
    return renderBrowserScreenshotToolSource(input, manifest);
  }
  if (input.kind === "browser-operate" || input.kind === "external-action-prepare") {
    return renderBrowserOperateToolSource(input, manifest);
  }
  if (input.kind === "web-search") {
    return renderWebSearchToolSource(input, manifest);
  }
  if (input.kind === "web-read") {
    return renderWebReadToolSource(input, manifest);
  }
  if (input.kind === "external-action-commit") return renderExternalActionCommitToolSource(input, manifest);
  if (input.kind === "npm-default-function") {
    const packageName = input.adapterPackageName ?? Object.keys(input.dependencies)[0];
    if (!packageName) throw new Error("npm-default-function tools require at least one dependency");
    const adapterContract = input.adapterContract ?? {
      packageName,
      importStyle: "default" as const,
      inputMode: "text-options" as const,
      evidence: "Default callable adapter contract.",
    };
    return [
      "import type { Tool } from \"../tool.js\";",
      `import * as packageModule from ${JSON.stringify(packageName)};`,
      "",
      `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
      `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
      "type AdapterContract = {",
      "  packageName: string;",
      "  importStyle: \"default\" | \"named\" | \"namespace\";",
      "  exportName?: string;",
      "  memberName?: string;",
      "  inputMode: \"text-options\" | \"object\";",
      "  inputSchema?: { type: \"object\"; properties: Record<string, unknown>; required?: string[] };",
      "  inputExample?: Record<string, unknown>;",
      "  evidence: string;",
      "};",
      `const adapterContract: AdapterContract = ${JSON.stringify(adapterContract, null, 2)};`,
      "",
      "type CallablePackage = (...args: unknown[]) => unknown;",
      "",
      "function resolveCallable(moduleValue: unknown): CallablePackage | undefined {",
      "  const record = moduleValue && typeof moduleValue === \"object\" ? moduleValue as Record<string, unknown> : {};",
      "  const defaultRecord = record.default && typeof record.default === \"object\"",
      "    ? record.default as Record<string, unknown>",
      "    : {};",
      "  const candidate = adapterContract.importStyle === \"named\"",
      "    ? record[adapterContract.exportName ?? \"\"] ?? defaultRecord[adapterContract.exportName ?? \"\"]",
      "    : adapterContract.importStyle === \"namespace\"",
      "      ? record[adapterContract.memberName ?? \"\"] ?? defaultRecord[adapterContract.memberName ?? \"\"]",
      "      : record.default ?? moduleValue;",
      "  if (typeof candidate === \"function\") {",
      "    return candidate as CallablePackage;",
      "  }",
      "  return undefined;",
      "}",
      "",
      "export const tool: Tool = {",
      `  name: ${JSON.stringify(input.name)},`,
      `  displayName: ${JSON.stringify(input.displayName)},`,
      `  version: ${JSON.stringify(input.version)},`,
      `  description: ${JSON.stringify(input.description)},`,
      `  capabilities: ${JSON.stringify(input.capabilities)},`,
      `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
      "  inputSchema,",
      "  outputSchema,",
      "  async healthcheck() {",
      "    const callable = resolveCallable(packageModule);",
      `    return callable ? { ok: true, detail: ${JSON.stringify(`${packageName} adapter contract loaded.`)} } : { ok: false, detail: ${JSON.stringify(`${packageName} did not satisfy the adapter contract.`)} };`,
      "  },",
      "  async run(input) {",
      "    const callable = resolveCallable(packageModule);",
      "    if (!callable) {",
      `      return { ok: false, content: ${JSON.stringify(`${packageName} did not satisfy the adapter contract.`)} };`,
      "    }",
      "    const args = buildCallArguments(input);",
      "    if (!args.ok) return args.result;",
      "    const value = await callable(...args.args);",
      "    const content = typeof value === \"string\" ? value : JSON.stringify(value);",
      "    return { ok: true, content, data: { packageName: " + JSON.stringify(packageName) + ", adapterContract } };",
      "  },",
      "};",
      "",
      "function buildCallArguments(input: Record<string, unknown>): { ok: true; args: unknown[] } | { ok: false; result: { ok: false; content: string } } {",
      "  if (adapterContract.inputMode === \"object\") {",
      "    const missing = (adapterContract.inputSchema?.required ?? []).filter((key) => input[key] === undefined);",
      "    if (missing.length > 0) {",
      "      return { ok: false, result: { ok: false, content: `missing required input: ${missing.join(\", \")}` } };",
      "    }",
      "    return { ok: true, args: [input] };",
      "  }",
      "  const text = typeof input.text === \"string\" ? input.text : \"\";",
      "  if (!text.trim()) return { ok: false, result: { ok: false, content: \"text is required\" } };",
      "  const options = input.options && typeof input.options === \"object\" && !Array.isArray(input.options)",
      "    ? input.options as Record<string, unknown>",
      "    : {};",
      "  return { ok: true, args: [text, options] };",
      "}",
      "",
    ].join("\n");
  }
  if (input.kind === "service-adapter") {
    if (
      input.integrationContract?.protocol === "messaging-bot" &&
      input.integrationContract.provider?.toLowerCase() === "telegram"
    ) {
      return renderTelegramMessagingServiceSource(input, manifest);
    }
    return [
      "import type { Tool } from \"../tool.js\";",
      "",
      `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
      `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
      `const integration = ${JSON.stringify(input.integrationContract, null, 2)} as any;`,
      "",
      "export const tool: Tool = {",
      `  name: ${JSON.stringify(input.name)},`,
      `  displayName: ${JSON.stringify(input.displayName)},`,
      `  version: ${JSON.stringify(input.version)},`,
      `  description: ${JSON.stringify(input.description)},`,
      `  capabilities: ${JSON.stringify(input.capabilities)},`,
      `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
      "  inputSchema,",
      "  outputSchema,",
      "  async healthcheck() {",
      "    return { ok: true, detail: `Service adapter contract loaded (${integration?.protocol ?? \"custom\"}).` };",
      "  },",
      "  async startService(context) {",
      "    return {",
      "      async stop() {",
      "        // The scaffold has no provider loop yet. LLM/provider authoring must replace this with a real adapter.",
      "      },",
      "      async healthcheck() {",
      "        return { ok: true, detail: \"Service adapter scaffold is running without a provider loop.\" };",
      "      },",
      "    };",
      "  },",
      "  async run(input) {",
      "    const event = normalizeManualEvent(input);",
      "    return {",
      "      ok: true,",
      "      content: event.text ? `Accepted integration event: ${event.text}` : \"Accepted integration event.\",",
      "      data: { event, integration },",
      "    };",
      "  },",
      "};",
      "",
      "function normalizeManualEvent(input: Record<string, unknown>): Record<string, unknown> {",
      "  const event = input.event && typeof input.event === \"object\" && !Array.isArray(input.event)",
      "    ? input.event as Record<string, unknown>",
      "    : {};",
      "  return {",
      "    ...event,",
      "    text: typeof input.text === \"string\" ? input.text : typeof event.text === \"string\" ? event.text : undefined,",
      "    sourceChannelId: typeof input.sourceChannelId === \"string\" ? input.sourceChannelId : event.sourceChannelId,",
      "    sourceUserId: typeof input.sourceUserId === \"string\" ? input.sourceUserId : event.sourceUserId,",
      "  };",
      "}",
      "",
    ].join("\n");
  }
  if (input.kind === "http-json") {
    return renderHttpJsonToolSource(input, manifest);
  }
  return [
    "import type { Tool } from \"../tool.js\";",
    "",
    `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
    `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
    "",
    "export const tool: Tool = {",
    `  name: ${JSON.stringify(input.name)},`,
    `  displayName: ${JSON.stringify(input.displayName)},`,
    `  version: ${JSON.stringify(input.version)},`,
    `  description: ${JSON.stringify(input.description)},`,
    `  capabilities: ${JSON.stringify(input.capabilities)},`,
    `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
    "  inputSchema,",
    "  outputSchema,",
    "  async healthcheck() {",
    "    return { ok: true, detail: \"Tool package loaded.\" };",
    "  },",
    "  async run(input) {",
    "    const text = typeof input.text === \"string\" ? input.text : JSON.stringify(input);",
    "    return { ok: true, content: text, data: { echoed: input } };",
    "  },",
    "};",
    "",
  ].join("\n");
}

export function renderToolTest(input: ToolCreationV1Result["input"], fileBase: string): string {
  if (input.kind === "npm-default-function") {
    const packageName = input.adapterPackageName ?? Object.keys(input.dependencies)[0] ?? "npm package";
    const adapterContract = input.adapterContract;
    if (adapterContract?.inputMode === "object") {
      const required = adapterContract.inputSchema?.required ?? [];
      const missingAssertion = required.length > 0
        ? [
            `test(${JSON.stringify(`${packageName} adapter validates object input`)}, async () => {`,
            "  const missing = await tool.run({});",
            "  assert.equal(missing.ok, false);",
            "  assert.match(missing.content, /missing required input/);",
            "});",
            "",
          ]
        : [];
      const example = input.behaviorExamples[0]?.input
        ?? adapterContract.inputExample
        ?? Object.fromEntries(required.map((field) => [field, exampleValueForSchema(adapterContract.inputSchema?.properties[field])]));
      return [
        "import test from \"node:test\";",
        "import assert from \"node:assert/strict\";",
        `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
        "",
        ...missingAssertion,
        `test(${JSON.stringify(`${packageName} adapter calls object input`)}, async () => {`,
        "  const health = await tool.healthcheck?.();",
        "  assert.equal(health?.ok, true);",
        `  const result = await tool.run(${JSON.stringify(example, null, 2)});`,
        "  assert.equal(result.ok, true);",
        "  assert.equal(typeof result.content, \"string\");",
        "  assert.ok(result.content.length > 0);",
        "});",
        "",
      ].join("\n");
    }
    return [
      "import test from \"node:test\";",
      "import assert from \"node:assert/strict\";",
      `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
      "",
      `test(${JSON.stringify(`${packageName} adapter validates text input`)}, async () => {`,
      "  const missing = await tool.run({});",
      "  assert.equal(missing.ok, false);",
      "  assert.match(missing.content, /text is required/);",
      "});",
      "",
      `test(${JSON.stringify(`${packageName} adapter exposes a callable transform`)}, async () => {`,
      "  const health = await tool.healthcheck?.();",
      "  assert.equal(health?.ok, true);",
      "  const result = await tool.run({ text: \"Hello World\", options: {} });",
      "  assert.equal(result.ok, true);",
      "  assert.equal(typeof result.content, \"string\");",
      "  assert.ok(result.content.length > 0);",
      "});",
      "",
    ].join("\n");
  }
  if (input.kind === "http-json") {
    return [
      "import test from \"node:test\";",
      "import assert from \"node:assert/strict\";",
      `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
      "",
      "test(\"http-json tool validates url input\", async () => {",
      "  const result = await tool.run({ url: \"file:///tmp/example.json\" });",
      "  assert.equal(result.ok, false);",
      "  assert.match(result.content, /http or https/);",
      "});",
      "",
    ].join("\n");
  }
  if (input.kind === "web-search") {
    return [
      "import test from \"node:test\";",
      "import assert from \"node:assert/strict\";",
      `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
      "",
      "test(\"web search tool validates query input\", async () => {",
      "  const result = await tool.run({});",
      "  assert.equal(result.ok, false);",
      "  assert.match(result.content, /query is required/);",
      "});",
      "",
      "test(\"web search tool exposes healthcheck\", async () => {",
      "  const health = await tool.healthcheck?.();",
      "  assert.equal(health?.ok, true);",
      "  assert.match(health?.detail ?? \"\", /Web search tool loaded/);",
      "});",
      "",
    ].join("\n");
  }
  if (input.kind === "web-read") {
    return [
      "import test from \"node:test\";",
      "import assert from \"node:assert/strict\";",
      `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
      "",
      "test(\"web read tool validates url input\", async () => {",
      "  const result = await tool.run({});",
      "  assert.equal(result.ok, false);",
      "  assert.match(result.content, /url is required/);",
      "  const invalidProtocol = await tool.run({ url: \"file:///tmp/example.html\" });",
      "  assert.equal(invalidProtocol.ok, false);",
      "  assert.match(invalidProtocol.content, /http or https/);",
      "});",
      "",
      "test(\"web read tool exposes healthcheck\", async () => {",
      "  const health = await tool.healthcheck?.();",
      "  assert.equal(health?.ok, true);",
      "  assert.match(health?.detail ?? \"\", /Web read tool loaded/);",
      "});",
      "",
    ].join("\n");
  }
  if (input.kind === "browser-screenshot") {
    return [
      "import test from \"node:test\";",
      "import assert from \"node:assert/strict\";",
      `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
      "",
      "test(\"browser screenshot tool validates url input\", async () => {",
      "  const missing = await tool.run({});",
      "  assert.equal(missing.ok, false);",
      "  assert.match(missing.content, /url is required/);",
      "  const invalidProtocol = await tool.run({ url: \"file:///tmp/example.html\" });",
      "  assert.equal(invalidProtocol.ok, false);",
      "  assert.match(invalidProtocol.content, /http or https/);",
      "});",
      "",
      "test(\"browser screenshot tool exposes healthcheck\", async () => {",
      "  const health = await tool.healthcheck?.();",
      "  assert.equal(health?.ok, true);",
      "  assert.match(health?.detail ?? \"\", /Browser screenshot tool loaded/);",
      "});",
      "",
    ].join("\n");
  }
  if (input.kind === "browser-operate" || input.kind === "external-action-prepare") {
    return [
      "import test from \"node:test\";",
      "import assert from \"node:assert/strict\";",
      `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
      "",
      "test(\"browser preparation tool validates URL protocol and prepare-only commit boundary\", async () => {",
      "  const invalid = await tool.run({ url: \"file:///tmp/example.html\" });",
      "  assert.equal(invalid.ok, false);",
      "  assert.match(invalid.content, /http or https/);",
      "  const health = await tool.healthcheck?.();",
      "  assert.equal(health?.ok, true);",
      "  assert.match(health?.detail ?? \"\", /Browser operate tool loaded/);",
      "});",
      "",
    ].join("\n");
  }
  if (input.kind === "external-action-commit") return renderExternalActionCommitToolTest(fileBase);
  if (input.kind === "service-adapter") {
    if (
      input.integrationContract?.protocol === "messaging-bot" &&
      input.integrationContract.provider?.toLowerCase() === "telegram"
    ) {
      return [
        "import test from \"node:test\";",
        "import assert from \"node:assert/strict\";",
        `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
        "",
        "test(\"telegram service adapter exposes lifecycle without network in test mode\", async () => {",
        "  assert.equal(tool.startupMode, \"always-on\");",
        "  const health = await tool.healthcheck?.();",
        "  assert.equal(health?.ok, true);",
        "  const handle = await tool.startService?.({ secrets: { \"secret.telegram.bot\": \"test-token\" } });",
        "  const handleHealth = await handle?.healthcheck?.();",
        "  assert.equal(handleHealth?.ok, true);",
        "  assert.match(handleHealth?.detail ?? \"\", /baseUrl/);",
        "  await handle?.stop?.();",
        "});",
        "",
        "test(\"telegram service adapter normalizes manual events\", async () => {",
        "  const result = await tool.run({ text: \"hello\", sourceChannelId: \"chat-1\", sourceUserId: \"user-1\" });",
        "  assert.equal(result.ok, true);",
        "  assert.match(result.content, /hello/);",
        "});",
        "",
      ].join("\n");
    }
    return [
      "import test from \"node:test\";",
      "import assert from \"node:assert/strict\";",
      `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
      "",
      "test(\"service adapter exposes always-on lifecycle\", async () => {",
      "  assert.equal(tool.startupMode, \"always-on\");",
      "  const health = await tool.healthcheck?.();",
      "  assert.equal(health?.ok, true);",
      "  const handle = await tool.startService?.({});",
      "  await handle?.stop?.();",
      "});",
      "",
      "test(\"service adapter accepts normalized manual event\", async () => {",
      "  const result = await tool.run({ text: \"hello\", sourceChannelId: \"chat-1\", sourceUserId: \"user-1\" });",
      "  assert.equal(result.ok, true);",
      "  assert.match(result.content, /hello/);",
      "});",
      "",
    ].join("\n");
  }
  return [
    "import test from \"node:test\";",
    "import assert from \"node:assert/strict\";",
    `import { tool } from "../../src/tools/generated/${fileBase}Tool.js";`,
    "",
    "test(\"echo tool returns text input\", async () => {",
    "  const result = await tool.run({ text: \"ok\" });",
    "  assert.equal(result.ok, true);",
    "  assert.equal(result.content, \"ok\");",
    "});",
    "",
  ].join("\n");
}

export function exampleValueForSchema(schema: unknown): unknown {
  if (!schema || typeof schema !== "object" || Array.isArray(schema)) return "example";
  const type = (schema as Record<string, unknown>).type;
  if (type === "number" || type === "integer") return 1;
  if (type === "boolean") return true;
  if (type === "array") return [];
  if (type === "object") return {};
  return "example";
}

function renderTelegramMessagingServiceSource(input: ToolCreationV1Result["input"], manifest: Omit<ToolPackageManifest, "package">): string {
  const secretHandle = input.integrationContract?.auth?.requiredSecretHandles?.[0] ?? "secret.telegram.bot";
  return [
    "import type { Tool } from \"../tool.js\";",
    "",
    `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
    `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
    `const integration = ${JSON.stringify(input.integrationContract, null, 2)} as any;`,
    `const secretHandle = ${JSON.stringify(secretHandle)};`,
    "const telegramApiBase = \"https://api.telegram.org\";",
    "const pollIntervalMs = 1500;",
    "",
    "type ServiceContext = {",
    "  baseUrl?: string;",
    "  secrets?: Record<string, string>;",
    "  missingSecretHandles?: string[];",
    "  signal?: AbortSignal;",
    "};",
    "",
    "export const tool: Tool = {",
    `  name: ${JSON.stringify(input.name)},`,
    `  displayName: ${JSON.stringify(input.displayName)},`,
    `  version: ${JSON.stringify(input.version)},`,
    `  description: ${JSON.stringify(input.description)},`,
    `  capabilities: ${JSON.stringify(input.capabilities)},`,
    `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
    "  inputSchema,",
    "  outputSchema,",
    "  async healthcheck() {",
    "    return { ok: true, detail: \"Telegram messaging service adapter loaded.\" };",
    "  },",
    "  async startService(rawContext) {",
    "    const context = normalizeServiceContext(rawContext);",
    "    const token = resolveTelegramToken(context);",
    "    if (!context.baseUrl) {",
    "      return {",
    "        async stop() {},",
    "        async healthcheck() {",
    "          return { ok: true, detail: \"Telegram token resolved; no Agentic baseUrl supplied, so provider loop is disabled for local package tests.\" };",
    "        },",
    "      };",
    "    }",
    "    const state = startTelegramBridge({",
    "      token,",
    "      agenticBaseUrl: context.baseUrl,",
    `      toolName: ${JSON.stringify(input.name)},`,
    "      signal: context.signal,",
    "    });",
    "    return {",
    "      async stop() { state.stop(); },",
    "      async healthcheck() {",
    "        return {",
    "          ok: !state.stopped,",
    "          detail: `Telegram bridge ${state.stopped ? \"stopped\" : \"running\"}; inbound=${state.inboundCount}; outbound=${state.outboundCount}; failures=${state.failureCount}.`,",
    "        };",
    "      },",
    "    };",
    "  },",
    "  async run(input) {",
    "    const event = normalizeManualEvent(input);",
    "    return {",
    "      ok: true,",
    "      content: event.text ? `Accepted Telegram integration event: ${event.text}` : \"Accepted Telegram integration event.\",",
    "      data: { event, integration },",
    "    };",
    "  },",
    "};",
    "",
    "function normalizeServiceContext(value: unknown): ServiceContext {",
    "  if (!value || typeof value !== \"object\" || Array.isArray(value)) return {};",
    "  return value as ServiceContext;",
    "}",
    "",
    "function resolveTelegramToken(context: ServiceContext): string {",
    "  const token = context.secrets?.[secretHandle];",
    "  if (typeof token === \"string\" && token.trim()) return token.trim();",
    "  const missing = context.missingSecretHandles?.length ? context.missingSecretHandles.join(\", \") : secretHandle;",
    "  throw new Error(`Missing required secret handle for Telegram service: ${missing}`);",
    "}",
    "",
    "function startTelegramBridge(options: { token: string; agenticBaseUrl: string; toolName: string; signal?: AbortSignal }) {",
    "  let stopped = false;",
    "  let timer: ReturnType<typeof setTimeout> | undefined;",
    "  let offset: number | undefined;",
    "  let inFlight = false;",
    "  const state = { inboundCount: 0, outboundCount: 0, failureCount: 0, get stopped() { return stopped; }, stop, };",
    "  options.signal?.addEventListener(\"abort\", stop, { once: true });",
    "  schedule(0);",
    "  return state;",
    "",
    "  function stop() {",
    "    stopped = true;",
    "    if (timer) clearTimeout(timer);",
    "  }",
    "",
    "  function schedule(delay: number) {",
    "    if (stopped) return;",
    "    timer = setTimeout(() => { void tick(); }, delay);",
    "  }",
    "",
    "  async function tick() {",
    "    if (stopped || inFlight) return;",
    "    inFlight = true;",
    "    try {",
    "      await receiveTelegramUpdates(options);",
    "      await deliverQueuedOutbox(options);",
    "    } catch (error) {",
    "      state.failureCount += 1;",
    "      console.warn(\"Telegram bridge tick failed\", error instanceof Error ? error.message : String(error));",
    "    } finally {",
    "      inFlight = false;",
    "      schedule(pollIntervalMs);",
    "    }",
    "  }",
    "",
    "  async function receiveTelegramUpdates(input: { token: string; agenticBaseUrl: string; toolName: string }) {",
    "    const url = new URL(`${telegramApiBase}/bot${input.token}/getUpdates`);",
    "    url.searchParams.set(\"timeout\", \"10\");",
    "    if (offset !== undefined) url.searchParams.set(\"offset\", String(offset));",
    "    const response = await fetch(url);",
    "    const body = await response.json() as { ok?: boolean; result?: unknown[]; description?: string };",
    "    if (!response.ok || body.ok === false) throw new Error(body.description ?? `Telegram getUpdates failed: ${response.status}`);",
    "    for (const update of Array.isArray(body.result) ? body.result : []) {",
    "      const updateId = readNumber(update, \"update_id\");",
    "      if (updateId !== undefined) offset = updateId + 1;",
    "      const event = telegramUpdateToInbound(update);",
    "      if (!event) continue;",
    "      await postJson(`${input.agenticBaseUrl}/api/tool-services/${encodeURIComponent(input.toolName)}/inbound`, event);",
    "      state.inboundCount += 1;",
    "    }",
    "  }",
    "",
    "  async function deliverQueuedOutbox(input: { token: string; agenticBaseUrl: string; toolName: string }) {",
    "    const url = `${input.agenticBaseUrl}/api/tool-services/${encodeURIComponent(input.toolName)}/outbox?limit=10`;",
    "    const payload = await getJson(url) as { events?: Array<Record<string, unknown>> };",
    "    for (const event of payload.events ?? []) {",
    "      const chatId = typeof event.sourceChatId === \"string\" ? event.sourceChatId : undefined;",
    "      const text = outboundText(event);",
    "      const artifacts = outboundArtifacts(event);",
    "      if (!chatId || (!text && artifacts.length === 0)) continue;",
    "      try {",
    "        const sentMessages: string[] = [];",
    "        const artifactFailures: string[] = [];",
    "        if (text) {",
    "          const sent = await sendTelegramMessage(input.token, chatId, text);",
    "          if (sent.messageId) sentMessages.push(sent.messageId);",
    "        }",
    "        for (const artifact of artifacts) {",
    "          try {",
    "            const sent = await sendTelegramArtifact(input.token, chatId, input.agenticBaseUrl, artifact);",
    "            if (sent.messageId) sentMessages.push(sent.messageId);",
    "          } catch (error) {",
    "            artifactFailures.push(error instanceof Error ? error.message : String(error));",
    "          }",
    "        }",
    "        if (artifactFailures.length > 0) state.failureCount += 1;",
    "        await postJson(`${input.agenticBaseUrl}/api/tool-services/${encodeURIComponent(input.toolName)}/outbox/${encodeURIComponent(String(event.id))}/ack`, {",
    "          status: \"sent\",",
    "          providerMessageId: sentMessages[0],",
    "          detail: artifactFailures.length > 0 ? `Artifact delivery failed: ${artifactFailures.join(\"; \")}` : undefined,",
    "          summary: artifactFailures.length > 0",
    "            ? `Telegram text sent to chat ${chatId}; ${artifactFailures.length} artifact(s) failed`",
    "            : `Telegram message sent to chat ${chatId}`",
    "        });",
    "        state.outboundCount += 1;",
    "      } catch (error) {",
    "        await postJson(`${input.agenticBaseUrl}/api/tool-services/${encodeURIComponent(input.toolName)}/outbox/${encodeURIComponent(String(event.id))}/ack`, {",
    "          status: \"failed\",",
    "          detail: error instanceof Error ? error.message : String(error),",
    "          summary: `Telegram message failed for chat ${chatId}`",
    "        }).catch(() => undefined);",
    "        state.failureCount += 1;",
    "      }",
    "    }",
    "  }",
    "}",
    "",
    "function telegramUpdateToInbound(update: unknown): Record<string, unknown> | undefined {",
    "  const record = asRecord(update);",
    "  if (!record) return undefined;",
    "  const message = asRecord(record.message) ?? asRecord(record.edited_message);",
    "  if (!message) return undefined;",
    "  const text = typeof message.text === \"string\" ? message.text : typeof message.caption === \"string\" ? message.caption : undefined;",
    "  const attachments = telegramMessageAttachments(message);",
    "  if (!text?.trim() && attachments.length === 0) return undefined;",
    "  const chat = asRecord(message.chat);",
    "  const from = asRecord(message.from);",
    "  const reply = asRecord(message.reply_to_message);",
    "  const username = typeof from?.username === \"string\" ? from.username : undefined;",
    "  return {",
    "    task: text?.trim() || \"Telegram attachment received.\",",
    `    channel: ${JSON.stringify(input.name)},`,
    "    sourceChatId: idToString(chat?.id),",
    "    sourceUserId: idToString(from?.id),",
    "    sourceUserAliases: [username, username ? `@${username}` : undefined].filter(Boolean),",
    "    sourceMessageId: idToString(message.message_id),",
    "    replyToProviderMessageId: idToString(reply?.message_id),",
    "    replyToSourceMessageId: idToString(reply?.message_id),",
    "    replyToMessage: reply ? compactReplyMetadata(reply) : undefined,",
    "    sourceThreadId: idToString(message.message_thread_id),",
    "    attachments,",
    "    provider: \"telegram\",",
    "    providerUpdateId: idToString(record.update_id),",
    "  };",
    "}",
    "",
    "function outboundText(event: Record<string, unknown>): string | undefined {",
    "  const payload = asRecord(event.payload);",
    "  const finalAnswer = typeof payload?.finalAnswer === \"string\" ? payload.finalAnswer : undefined;",
    "  const error = typeof payload?.error === \"string\" ? payload.error : undefined;",
    "  const summary = typeof event.summary === \"string\" ? event.summary : undefined;",
    "  return (finalAnswer ?? error ?? summary)?.slice(0, 3900);",
    "}",
    "",
    ...telegramFormattingSourceLines(),
    "function outboundArtifacts(event: Record<string, unknown>): Array<Record<string, unknown>> {",
    "  const payload = asRecord(event.payload);",
    "  const raw = Array.isArray(payload?.artifacts)",
    "    ? payload.artifacts",
    "    : Array.isArray(payload?.artifactRefs)",
    "      ? payload.artifactRefs",
    "      : [];",
    "  return raw.map((item) => asRecord(item)).filter((item): item is Record<string, unknown> => Boolean(item));",
    "}",
    "",
    "async function sendTelegramMessage(token: string, chatId: string, text: string): Promise<{ messageId?: string }> {",
    "  const formatted = telegramMessageFromMarkdown(text);",
    "  let response = await postJson(`${telegramApiBase}/bot${token}/sendMessage`, { chat_id: chatId, ...formatted });",
    "  if (asRecord(response)?.ok === false && formatted.parse_mode) {",
    "    response = await postJson(`${telegramApiBase}/bot${token}/sendMessage`, { chat_id: chatId, text });",
    "  }",
    "  const result = asRecord((response as Record<string, unknown>).result);",
    "  return { messageId: idToString(result?.message_id) };",
    "}",
    "",
    "async function sendTelegramArtifact(token: string, chatId: string, agenticBaseUrl: string, artifact: Record<string, unknown>): Promise<{ messageId?: string }> {",
    "  const url = typeof artifact.url === \"string\" ? artifact.url : undefined;",
    "  if (!url) throw new Error(\"artifact is missing a downloadable url\");",
    "  const absoluteUrl = url.startsWith(\"http://\") || url.startsWith(\"https://\") ? url : `${agenticBaseUrl}${url.startsWith(\"/\") ? \"\" : \"/\"}${url}`;",
    "  const response = await fetch(absoluteUrl);",
    "  if (!response.ok) throw new Error(`artifact download failed: ${response.status}`);",
    "  const mimeType = typeof artifact.mimeType === \"string\" ? artifact.mimeType : response.headers.get(\"content-type\") ?? \"application/octet-stream\";",
    "  const filename = typeof artifact.filename === \"string\" && artifact.filename.trim() ? artifact.filename.trim() : \"artifact\";",
    "  const bytes = await response.arrayBuffer();",
    "  const blob = new Blob([bytes], { type: mimeType });",
    "  const form = new FormData();",
    "  form.set(\"chat_id\", chatId);",
    "  const caption = typeof artifact.description === \"string\" ? artifact.description.slice(0, 1024) : filename;",
    "  if (caption) form.set(\"caption\", caption);",
    "  const endpoint = mimeType.startsWith(\"image/\") ? \"sendPhoto\" : \"sendDocument\";",
    "  form.set(mimeType.startsWith(\"image/\") ? \"photo\" : \"document\", blob, filename);",
    "  const sent = await postForm(`${telegramApiBase}/bot${token}/${endpoint}`, form);",
    "  const result = asRecord((sent as Record<string, unknown>).result);",
    "  return { messageId: idToString(result?.message_id) };",
    "}",
    "",
    "async function getJson(url: string): Promise<unknown> {",
    "  const response = await fetch(url);",
    "  const text = await response.text();",
    "  const parsed = text ? JSON.parse(text) : {};",
    "  const parsedRecord = asRecord(parsed);",
    "  if (!response.ok) throw new Error(typeof parsedRecord?.error === \"string\" ? parsedRecord.error : `GET ${url} failed: ${response.status}`);",
    "  return parsed;",
    "}",
    "",
    "async function postJson(url: string, body: unknown): Promise<unknown> {",
    "  const response = await fetch(url, {",
    "    method: \"POST\",",
    "    headers: { \"content-type\": \"application/json\" },",
    "    body: JSON.stringify(body),",
    "  });",
    "  const text = await response.text();",
    "  const parsed = text ? JSON.parse(text) : {};",
    "  const parsedRecord = asRecord(parsed);",
    "  if (!response.ok) throw new Error(typeof parsedRecord?.error === \"string\" ? parsedRecord.error : `POST ${url} failed: ${response.status}`);",
    "  return parsed;",
    "}",
    "",
    "async function postForm(url: string, body: FormData): Promise<unknown> {",
    "  const response = await fetch(url, { method: \"POST\", body });",
    "  const text = await response.text();",
    "  const parsed = text ? JSON.parse(text) : {};",
    "  const parsedRecord = asRecord(parsed);",
    "  if (!response.ok) throw new Error(typeof parsedRecord?.description === \"string\" ? parsedRecord.description : `POST ${url} failed: ${response.status}`);",
    "  return parsed;",
    "}",
    "",
    "function normalizeManualEvent(input: Record<string, unknown>): Record<string, unknown> {",
    "  const event = input.event && typeof input.event === \"object\" && !Array.isArray(input.event)",
    "    ? input.event as Record<string, unknown>",
    "    : {};",
    "  return {",
    "    ...event,",
    "    text: typeof input.text === \"string\" ? input.text : typeof event.text === \"string\" ? event.text : undefined,",
    "    sourceChannelId: typeof input.sourceChannelId === \"string\" ? input.sourceChannelId : event.sourceChannelId,",
    "    sourceUserId: typeof input.sourceUserId === \"string\" ? input.sourceUserId : event.sourceUserId,",
    "  };",
    "}",
    "",
    "function telegramMessageAttachments(message: Record<string, unknown>): Array<Record<string, unknown>> {",
    "  const attachments: Array<Record<string, unknown>> = [];",
    "  const caption = typeof message.caption === \"string\" ? message.caption : undefined;",
    "  const photos = Array.isArray(message.photo) ? message.photo.map((item) => asRecord(item)).filter(Boolean) as Array<Record<string, unknown>> : [];",
    "  if (photos.length > 0) {",
    "    const photo = photos.reduce((best, item) => Number(item.file_size ?? 0) > Number(best.file_size ?? 0) ? item : best, photos[0]!);",
    "    attachments.push({",
    "      provider: \"telegram\",",
    "      type: \"photo\",",
    "      mimeType: \"image/jpeg\",",
    "      fileId: idToString(photo.file_id),",
    "      uniqueFileId: idToString(photo.file_unique_id),",
    "      sizeBytes: readNumber(photo, \"file_size\"),",
    "      caption,",
    "    });",
    "  }",
    "  for (const key of [\"document\", \"video\", \"animation\", \"audio\", \"voice\", \"video_note\", \"sticker\"]) {",
    "    const item = asRecord(message[key]);",
    "    if (!item) continue;",
    "    attachments.push({",
    "      provider: \"telegram\",",
    "      type: key,",
    "      mimeType: typeof item.mime_type === \"string\" ? item.mime_type : undefined,",
    "      filename: typeof item.file_name === \"string\" ? item.file_name : undefined,",
    "      fileId: idToString(item.file_id),",
    "      uniqueFileId: idToString(item.file_unique_id),",
    "      sizeBytes: readNumber(item, \"file_size\"),",
    "      caption,",
    "    });",
    "  }",
    "  return attachments.filter((attachment) => attachment.fileId);",
    "}",
    "",
    "function compactReplyMetadata(message: Record<string, unknown>): Record<string, unknown> {",
    "  const from = asRecord(message.from);",
    "  return {",
    "    providerMessageId: idToString(message.message_id),",
    "    sourceMessageId: idToString(message.message_id),",
    "    text: typeof message.text === \"string\" ? message.text : typeof message.caption === \"string\" ? message.caption : undefined,",
    "    sourceUserId: idToString(from?.id),",
    "    sourceUsername: typeof from?.username === \"string\" ? from.username : undefined,",
    "    attachments: telegramMessageAttachments(message),",
    "  };",
    "}",
    "",
    "function asRecord(value: unknown): Record<string, unknown> | undefined {",
    "  return value && typeof value === \"object\" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;",
    "}",
    "",
    "function readNumber(value: unknown, key: string): number | undefined {",
    "  const candidate = asRecord(value)?.[key];",
    "  return typeof candidate === \"number\" && Number.isFinite(candidate) ? candidate : undefined;",
    "}",
    "",
    "function idToString(value: unknown): string | undefined {",
    "  if (typeof value === \"string\" && value) return value;",
    "  if (typeof value === \"number\" && Number.isFinite(value)) return String(value);",
    "  return undefined;",
    "}",
    "",
  ].join("\n");
}
