import type { ToolCreationV1Result } from "./toolCreationV1.js";
import type { ToolPackageManifest } from "./toolPackage.js";

export function renderBrowserOperateToolSource(
  input: ToolCreationV1Result["input"],
  manifest: Omit<ToolPackageManifest, "package">,
): string {
  const capabilities = Array.from(
    new Set([
      ...input.capabilities,
      "browser-action-candidates",
      "browser-field-candidates",
      "browser-form-schema",
      "browser-interactive-fields",
      "browser-no-progress-detection",
      "browser-repeated-control-targeting",
      "browser-safe-advance",
    ]),
  );
  return [
    "import { existsSync, readdirSync } from \"node:fs\";",
    "import { homedir } from \"node:os\";",
    "import { join } from \"node:path\";",
    "import { chromium, type Locator, type Page } from \"playwright-core\";",
    "import type { Tool } from \"../tool.js\";",
    "",
    `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
    `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
    "",
    "type BrowserCommand = Record<string, unknown>;",
    "type StepRecord = { index: number; action: string; ok: boolean; detail: string; blocked?: boolean };",
    "type ParsedInput = {",
    "  url?: string;",
    "  commands: BrowserCommand[];",
    "  prepareOnly: boolean;",
    "  width: number;",
    "  height: number;",
    "  timeoutMs: number;",
    "  maxCommands: number;",
    "};",
    "",
    "const POSSIBLE_COMMIT_TARGET = /(book|reserve|reservation|reservar|reserva|schedule|appointment|cita|submit|confirm|send|pay|checkout|buy|purchase|place order|complete booking)/i;",
    "const FINAL_COMMIT_TARGET = /(confirm|submit|send|pay|checkout|buy|purchase|place order|complete booking|complete order|finalize|finish|confirmar|enviar|pagar|comprar|finalizar)/i;",
    "const SAFE_ADVANCE_TARGET = /(book|reserve|reservation|reservar|reserva|schedule|appointment|availability|select|choose|continue|next|cita|seleccionar|elegir|continuar|siguiente)/i;",
    "",
    "export const tool: Tool = {",
    `  name: ${JSON.stringify(input.name)},`,
    `  displayName: ${JSON.stringify(input.displayName)},`,
    `  version: ${JSON.stringify(input.version)},`,
    `  description: ${JSON.stringify(input.description)},`,
    `  capabilities: ${JSON.stringify(capabilities)},`,
    `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
    "  inputSchema,",
    "  outputSchema,",
    "  async healthcheck() {",
    "    const executablePath = resolveExecutablePath();",
    "    return {",
    "      ok: true,",
    "      detail: executablePath",
    "        ? `Browser operate tool loaded; Chromium executable found at ${executablePath}.`",
    "        : \"Browser operate tool loaded; Playwright will resolve Chromium at runtime.\",",
    "    };",
    "  },",
    "  async run(input) {",
    "    const parsed = parseInput(input);",
    "    if (!parsed.ok) return { ok: false, content: parsed.error };",
    "    const browser = await chromium.launch(browserLaunchOptions());",
    "    const steps: StepRecord[] = [];",
    "    const artifacts: unknown[] = [];",
    "    const data: Record<string, unknown> = { steps, artifacts };",
    "    try {",
    "      const page = await browser.newPage({ viewport: { width: parsed.value.width, height: parsed.value.height } });",
    "      page.setDefaultTimeout(parsed.value.timeoutMs);",
    "      if (parsed.value.url) {",
    "        await page.goto(parsed.value.url, { waitUntil: \"domcontentloaded\", timeout: parsed.value.timeoutMs });",
    "        steps.push({ index: 0, action: \"navigate\", ok: true, detail: page.url() });",
    "      }",
    "      if (parsed.value.commands.length === 0) {",
    "        parsed.value.commands.push({ action: \"extractText\" }, { action: \"screenshot\" });",
    "      }",
    "      for (let index = 0; index < parsed.value.commands.length; index += 1) {",
    "        const command = parsed.value.commands[index] ?? {};",
    "        const step = await runCommand(page, command, parsed.value, index + 1, artifacts);",
    "        steps.push(step);",
    "        if (!step.ok) {",
    "          return { ok: false, content: step.detail, data: await finalizeData(page, data) };",
    "        }",
    "      }",
    "      return {",
    "        ok: true,",
    "        content: `Browser operation completed: ${page.url()}`,",
    "        data: await finalizeData(page, data),",
    "      };",
    "    } finally {",
    "      await browser.close();",
    "    }",
    "  },",
    "};",
    "",
    "async function runCommand(page: Page, command: BrowserCommand, parsed: ParsedInput, index: number, artifacts: unknown[]): Promise<StepRecord> {",
    "  const action = commandName(command);",
    "  if (action === \"navigate\") {",
    "    const url = stringValue(command.url);",
    "    if (!url) return fail(index, action, \"navigate.url is required\");",
    "    const checked = httpUrl(url);",
    "    if (!checked.ok) return fail(index, action, checked.error);",
    "    await page.goto(checked.url, { waitUntil: \"domcontentloaded\", timeout: parsed.timeoutMs });",
    "    return ok(index, action, page.url());",
    "  }",
    "  if (action === \"dismissdialogs\" || action === \"dismissdialog\") {",
    "    const dismissed = await dismissCommonDialogs(page);",
    "    return ok(index, action, dismissed ? \"dismissed visible dialog\" : \"no visible dialog found\");",
    "  }",
    "  if (action === \"click\") {",
    "    const target = targetText(command);",
    "    if (parsed.prepareOnly && !booleanValue(command.allowCommit)) {",
    "      const safeAdvance = booleanValue(command.safeAdvance);",
    "      if (FINAL_COMMIT_TARGET.test(target) || (!safeAdvance && POSSIBLE_COMMIT_TARGET.test(target))) {",
    "        return { index, action, ok: false, blocked: true, detail: `blocked possible final commit target in prepareOnly mode: ${target}` };",
    "      }",
    "      if (safeAdvance && !SAFE_ADVANCE_TARGET.test(target)) {",
    "        return { index, action, ok: false, blocked: true, detail: `blocked unsafe prepare advance target: ${target}` };",
    "      }",
    "    }",
    "    const locator = await locatorFor(page, command);",
    "    if (!locator) return optionalSkip(index, action, command, \"click target not found\") ?? fail(index, action, \"click requires selector, text, role/name, label, placeholder, or testId\");",
    "    await locator.scrollIntoViewIfNeeded().catch(() => undefined);",
    "    const clickTimeoutMs = booleanValue(command.safeAdvance) ? Math.min(parsed.timeoutMs, 5000) : parsed.timeoutMs;",
    "    try {",
    "      await locator.click({ timeout: clickTimeoutMs });",
    "    } catch (error) {",
    "      if (booleanValue(command.safeAdvance)) {",
    "        try {",
    "          await locator.click({ timeout: clickTimeoutMs, force: true });",
    "          return ok(index, action, `clicked ${target || \"target\"} with safe-advance fallback`);",
    "        } catch {",
    "          await locator.evaluate((element) => {",
    "            if (element instanceof HTMLElement) element.click();",
    "          });",
    "          return ok(index, action, `clicked ${target || \"target\"} with DOM safe-advance fallback`);",
    "        }",
    "      }",
    "      const skipped = optionalSkip(index, action, command, `click target failed: ${error instanceof Error ? error.message : String(error)}`);",
    "      if (skipped) return skipped;",
    "      throw error;",
    "    }",
    "    return ok(index, action, `clicked ${target || \"target\"}`);",
    "  }",
    "  if (action === \"fill\" || action === \"type\") {",
    "    const value = stringValue(command.value ?? command.text);",
    "    if (value === undefined) return fail(index, action, `${action}.value is required`);",
    "    const locator = await locatorFor(page, command);",
    "    if (!locator) return optionalSkip(index, action, command, `${action} target not found`) ?? fail(index, action, `${action} requires selector, label, placeholder, or testId`);",
    "    try {",
    "      await locator.fill(value, { timeout: parsed.timeoutMs });",
    "    } catch (error) {",
    "      try {",
    "        await locator.click({ timeout: parsed.timeoutMs });",
    "        await page.keyboard.type(value, { delay: 5 });",
    "        return ok(index, action, \"typed into focused field fallback\");",
    "      } catch {",
    "        // Continue to the normal optional/failure path below.",
    "      }",
    "      const skipped = optionalSkip(index, action, command, `${action} target failed: ${error instanceof Error ? error.message : String(error)}`);",
    "      if (skipped) return skipped;",
    "      throw error;",
    "    }",
    "    return ok(index, action, \"filled field\");",
    "  }",
    "  if (action === \"selectoption\" || action === \"select\") {",
    "    const value = stringValue(command.value);",
    "    if (!value) return fail(index, action, \"selectOption.value is required\");",
    "    const locator = await locatorFor(page, command);",
    "    if (!locator) return optionalSkip(index, action, command, \"selectOption target not found\") ?? fail(index, action, \"selectOption requires selector, label, placeholder, or testId\");",
    "    try {",
    "      await locator.selectOption(value, { timeout: parsed.timeoutMs });",
    "    } catch (error) {",
    "      const skipped = optionalSkip(index, action, command, `selectOption target failed: ${error instanceof Error ? error.message : String(error)}`);",
    "      if (skipped) return skipped;",
    "      throw error;",
    "    }",
    "    return ok(index, action, `selected ${value}`);",
    "  }",
    "  if (action === \"waitforselector\") {",
    "    const selector = stringValue(command.selector);",
    "    if (!selector) return fail(index, action, \"waitForSelector.selector is required\");",
    "    await page.locator(selector).first().waitFor({ timeout: parsed.timeoutMs });",
    "    return ok(index, action, `selector visible: ${selector}`);",
    "  }",
    "  if (action === \"waitfortext\") {",
    "    const text = stringValue(command.text);",
    "    if (!text) return fail(index, action, \"waitForText.text is required\");",
    "    await page.getByText(text, { exact: false }).first().waitFor({ timeout: parsed.timeoutMs });",
    "    return ok(index, action, `text visible: ${text}`);",
    "  }",
    "  if (action === \"wait\" || action === \"sleep\") {",
    "    const ms = clampInteger(command.ms ?? command.timeoutMs, 500, 0, 10000);",
    "    await page.waitForTimeout(ms);",
    "    return ok(index, action, `waited ${ms}ms`);",
    "  }",
    "  if (action === \"extracttext\") {",
    "    const limit = clampInteger(command.limit, 8000, 200, 50000);",
    "    const text = compactText(await page.locator(\"body\").innerText({ timeout: parsed.timeoutMs }).catch(() => \"\"), limit);",
    "    (page as unknown as { __agenticExtractedText?: string }).__agenticExtractedText = text;",
    "    return ok(index, action, text || \"no page text extracted\");",
    "  }",
    "  if (action === \"extractlinks\") {",
    "    const limit = clampInteger(command.limit, 25, 1, 100);",
    "    const links = await page.locator(\"a[href]\").evaluateAll((nodes, max) => nodes.slice(0, Number(max)).map((node) => ({",
    "      text: (node.textContent ?? \"\").replace(/\\s+/g, \" \").trim(),",
    "      href: (node as HTMLAnchorElement).href,",
    "    })), limit).catch(() => []);",
    "    (page as unknown as { __agenticLinks?: unknown[] }).__agenticLinks = links;",
    "    return ok(index, action, JSON.stringify(links));",
    "  }",
    "  if (action === \"extractforms\" || action === \"extractform\") {",
    "    const limit = clampInteger(command.limit, 5, 1, 20);",
    "    const forms = (await page.locator(\"form\").evaluateAll((nodes) => {",
    "      const compact = (value: string | null | undefined) => {",
    "        const text = (value ?? \"\").replace(/\\s+/g, \" \").trim();",
    "        return text || undefined;",
    "      };",
    "      const cssEscape = (value: string) => value.replace(/([\"\\\\#.;?+*~':!^$[\\]()=>|/@])/g, \"\\\\$1\");",
    "      const cssPath = (element: Element) => {",
    "        const parts: string[] = [];",
    "        let current: Element | null = element;",
    "        while (current && current !== current.ownerDocument.body && parts.length < 4) {",
    "          const parent: Element | null = current.parentElement;",
    "          if (!parent) break;",
    "          const tag = current.tagName.toLowerCase();",
    "          const currentTag = current.tagName;",
    "          const siblings = (Array.from(parent.children) as Element[]).filter((child) => child.tagName === currentTag);",
    "          const position = Math.max(1, siblings.indexOf(current) + 1);",
    "          parts.unshift(`${tag}:nth-of-type(${position})`);",
    "          current = parent;",
    "        }",
    "        return parts.length ? parts.join(\" > \") : undefined;",
    "      };",
    "      const selectorFor = (element: Element) => {",
    "        const id = element.getAttribute(\"id\");",
    "        if (id) return `#${cssEscape(id)}`;",
    "        const testId = element.getAttribute(\"data-testid\") || element.getAttribute(\"data-test\") || element.getAttribute(\"data-qa\");",
    "        if (testId) return `[data-testid=\\\"${cssEscape(testId)}\\\"], [data-test=\\\"${cssEscape(testId)}\\\"], [data-qa=\\\"${cssEscape(testId)}\\\"]`;",
    "        const name = element.getAttribute(\"name\");",
    "        if (name) return `${element.tagName.toLowerCase()}[name=\\\"${cssEscape(name)}\\\"]`;",
    "        const aria = element.getAttribute(\"aria-label\");",
    "        if (aria) return `${element.tagName.toLowerCase()}[aria-label=\\\"${cssEscape(aria)}\\\"]`;",
    "        const placeholder = element.getAttribute(\"placeholder\");",
    "        if (placeholder) return `${element.tagName.toLowerCase()}[placeholder=\\\"${cssEscape(placeholder)}\\\"]`;",
    "        return cssPath(element);",
    "      };",
    "      return nodes.map((form, formIndex) => {",
    "      const documentLabels = Array.from(form.ownerDocument.querySelectorAll(\"label\"));",
    "      const fields = Array.from(form.querySelectorAll(\"input, textarea, select\")).slice(0, 80).map((element, index) => {",
    "        const control = element as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement;",
    "        const id = control.id || undefined;",
    "        const explicitLabel = id ? documentLabels.find((label) => label.htmlFor === id)?.textContent : undefined;",
    "        const wrappedLabel = control.closest(\"label\")?.textContent;",
    "        return {",
    "          index,",
    "          tagName: element.tagName.toLowerCase(),",
    "          type: control.getAttribute(\"type\") || element.tagName.toLowerCase(),",
    "          name: control.getAttribute(\"name\") || undefined,",
    "          id,",
    "          selector: selectorFor(element),",
    "          label: compact(explicitLabel || wrappedLabel),",
    "          placeholder: control.getAttribute(\"placeholder\") || undefined,",
    "          autocomplete: control.getAttribute(\"autocomplete\") || undefined,",
    "          required: control.hasAttribute(\"required\"),",
    "        };",
    "      });",
    "      const submitCandidates = Array.from(form.querySelectorAll(\"button, input[type='submit'], input[type='button']\")).slice(0, 20).map((element, index) => {",
    "        const control = element as HTMLButtonElement | HTMLInputElement;",
    "        const context = element.closest(\"li, article, section, [role='listitem'], [data-testid*='service'], [class*='service'], [class*='card'], [class*='item']\") || element.parentElement;",
    "        return {",
    "          index,",
    "          tagName: element.tagName.toLowerCase(),",
    "          type: control.getAttribute(\"type\") || element.tagName.toLowerCase(),",
          "          text: compact(element.textContent || control.getAttribute(\"value\")),",
          "          name: control.getAttribute(\"name\") || undefined,",
          "          id: control.id || undefined,",
          "          selector: selectorFor(element),",
          "          nearText: compact(context?.textContent),",
        "        };",
    "      });",
    "      return {",
    "        formIndex,",
    "        action: form.getAttribute(\"action\") || undefined,",
    "        method: form.getAttribute(\"method\") || undefined,",
    "        fields,",
    "        submitCandidates,",
    "      };",
    "    });",
    "    }).catch(() => [])).slice(0, limit);",
    "    const actionCandidates = await extractActionCandidates(page, Math.max(20, limit * 3));",
    "    const pageFields = await extractPageFields(page, 80);",
    "    const syntheticPageForm = pageFields.length",
    "      ? [{ formIndex: forms.length, scope: \"page\", fields: pageFields, submitCandidates: actionCandidates.slice(0, 20) }]",
    "      : [];",
    "    const allForms = [...forms, ...syntheticPageForm].slice(0, limit);",
    "    (page as unknown as { __agenticForms?: unknown[] }).__agenticForms = allForms;",
    "    (page as unknown as { __agenticActionCandidates?: unknown[] }).__agenticActionCandidates = actionCandidates;",
    "    return ok(index, action, JSON.stringify(allForms));",
    "  }",
    "  if (action === \"screenshot\") {",
    "    const buffer = await page.screenshot({ fullPage: booleanValue(command.fullPage), type: \"png\" });",
    "    const filename = safeFilename(stringValue(command.filename) ?? `${slugForFilename(new URL(page.url()).hostname || \"browser\")}.png`);",
    "    artifacts.push({",
    "      filename,",
    "      mimeType: \"image/png\",",
    "      contentBase64: buffer.toString(\"base64\"),",
    "      description: `Viewport screenshot captured from ${page.url()}`,",
    "    });",
    "    return ok(index, action, filename);",
    "  }",
    "  return fail(index, action, `unsupported browser command: ${action}`);",
    "}",
    "",
    "async function finalizeData(page: Page, data: Record<string, unknown>): Promise<Record<string, unknown>> {",
    "  const extra = page as unknown as { __agenticExtractedText?: string; __agenticLinks?: unknown[]; __agenticForms?: unknown[]; __agenticActionCandidates?: unknown[] };",
    "  return {",
    "    ...data,",
    "    finalUrl: page.url(),",
    "    pageTitle: await page.title().catch(() => undefined),",
    "    extractedText: extra.__agenticExtractedText,",
    "    links: extra.__agenticLinks,",
    "    forms: extra.__agenticForms,",
    "    actionCandidates: extra.__agenticActionCandidates,",
    "  };",
    "}",
    "",
    "async function extractPageFields(page: Page, limit: number): Promise<unknown[]> {",
    "  const selector = \"input, textarea, select, [contenteditable='true'], [role='textbox'], [role='combobox'], [role='searchbox'], [role='spinbutton']\";",
    "  return page.locator(selector).evaluateAll((nodes, max) => {",
    "    const compact = (value: string | null | undefined) => {",
    "      const text = (value ?? \"\").replace(/\\s+/g, \" \").trim();",
    "      return text || undefined;",
    "    };",
    "    const cssEscape = (value: string) => value.replace(/([\"\\\\#.;?+*~':!^$[\\]()=>|/@])/g, \"\\\\$1\");",
    "    const cssPath = (element: Element) => {",
    "      const parts: string[] = [];",
    "      let current: Element | null = element;",
    "      while (current && current !== current.ownerDocument.body && parts.length < 4) {",
    "        const parent: Element | null = current.parentElement;",
    "        if (!parent) break;",
    "        const tag = current.tagName.toLowerCase();",
    "        const currentTag = current.tagName;",
    "        const siblings = (Array.from(parent.children) as Element[]).filter((child) => child.tagName === currentTag);",
    "        const position = Math.max(1, siblings.indexOf(current) + 1);",
    "        parts.unshift(`${tag}:nth-of-type(${position})`);",
    "        current = parent;",
    "      }",
    "      return parts.length ? parts.join(\" > \") : undefined;",
    "    };",
    "    const selectorFor = (element: Element) => {",
    "      const id = element.getAttribute(\"id\");",
    "      if (id) return `#${cssEscape(id)}`;",
    "      const testId = element.getAttribute(\"data-testid\") || element.getAttribute(\"data-test\") || element.getAttribute(\"data-qa\");",
    "      if (testId) return `[data-testid=\\\"${cssEscape(testId)}\\\"], [data-test=\\\"${cssEscape(testId)}\\\"], [data-qa=\\\"${cssEscape(testId)}\\\"]`;",
    "      const name = element.getAttribute(\"name\");",
    "      if (name) return `${element.tagName.toLowerCase()}[name=\\\"${cssEscape(name)}\\\"]`;",
    "      const aria = element.getAttribute(\"aria-label\");",
    "      if (aria) return `${element.tagName.toLowerCase()}[aria-label=\\\"${cssEscape(aria)}\\\"]`;",
    "      const placeholder = element.getAttribute(\"placeholder\");",
    "      if (placeholder) return `${element.tagName.toLowerCase()}[placeholder=\\\"${cssEscape(placeholder)}\\\"]`;",
    "      return cssPath(element);",
    "    };",
    "    return nodes.slice(0, Number(max)).map((element, index) => {",
    "      const control = element as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement;",
    "      const id = control.id || undefined;",
    "      const labels = Array.from(element.ownerDocument.querySelectorAll(\"label\"));",
    "      const explicitLabel = id ? labels.find((label) => label.htmlFor === id)?.textContent : undefined;",
    "      const wrappedLabel = control.closest(\"label\")?.textContent;",
    "      const role = element.getAttribute(\"role\") || undefined;",
    "      return {",
    "        index,",
    "        scope: \"page\",",
    "        tagName: element.tagName.toLowerCase(),",
    "        type: control.getAttribute(\"type\") || role || element.tagName.toLowerCase(),",
    "        name: control.getAttribute(\"name\") || undefined,",
    "        id,",
    "        selector: selectorFor(element),",
    "        label: compact(explicitLabel || wrappedLabel || element.getAttribute(\"aria-label\")),",
    "        placeholder: control.getAttribute(\"placeholder\") || undefined,",
    "        autocomplete: control.getAttribute(\"autocomplete\") || undefined,",
    "        required: control.hasAttribute(\"required\") || element.getAttribute(\"aria-required\") === \"true\",",
    "        contentEditable: element.getAttribute(\"contenteditable\") === \"true\" || undefined,",
    "      };",
    "    });",
    "  }, limit).catch(() => []);",
    "}",
    "",
    "async function extractActionCandidates(page: Page, limit: number): Promise<unknown[]> {",
    "  return page.locator(\"button, [role='button'], a[href], input[type='submit'], input[type='button']\").evaluateAll((nodes, max) => {",
    "    const compact = (value: string | null | undefined) => {",
    "      const text = (value ?? \"\").replace(/\\s+/g, \" \").trim();",
    "      return text || undefined;",
    "    };",
    "    const cssEscape = (value: string) => value.replace(/([\"\\\\#.;?+*~':!^$[\\]()=>|/@])/g, \"\\\\$1\");",
    "    const cssPath = (element: Element) => {",
    "      const parts: string[] = [];",
    "      let current: Element | null = element;",
    "      while (current && current !== current.ownerDocument.body && parts.length < 4) {",
    "        const parent: Element | null = current.parentElement;",
    "        if (!parent) break;",
    "        const tag = current.tagName.toLowerCase();",
    "        const currentTag = current.tagName;",
    "        const siblings = (Array.from(parent.children) as Element[]).filter((child) => child.tagName === currentTag);",
    "        const position = Math.max(1, siblings.indexOf(current) + 1);",
    "        parts.unshift(`${tag}:nth-of-type(${position})`);",
    "        current = parent;",
    "      }",
    "      return parts.length ? parts.join(\" > \") : undefined;",
    "    };",
    "    const selectorFor = (element: Element) => {",
    "      const id = element.getAttribute(\"id\");",
    "      if (id) return `#${cssEscape(id)}`;",
    "      const testId = element.getAttribute(\"data-testid\") || element.getAttribute(\"data-test\") || element.getAttribute(\"data-qa\");",
    "      if (testId) return `[data-testid=\\\"${cssEscape(testId)}\\\"], [data-test=\\\"${cssEscape(testId)}\\\"], [data-qa=\\\"${cssEscape(testId)}\\\"]`;",
    "      const name = element.getAttribute(\"name\");",
    "      if (name) return `${element.tagName.toLowerCase()}[name=\\\"${cssEscape(name)}\\\"]`;",
    "      const aria = element.getAttribute(\"aria-label\");",
    "      if (aria) return `${element.tagName.toLowerCase()}[aria-label=\\\"${cssEscape(aria)}\\\"]`;",
    "      return cssPath(element);",
    "    };",
    "    const actionable = /(book|reserve|reservation|reservar|reserva|confirm|submit|send|schedule|appointment|cita|continuar|continue|next|siguiente|select|seleccionar|choose|elegir|availability)/i;",
    "    const finalCommit = /(confirm|submit|send|pay|checkout|buy|purchase|place order|complete booking|complete order|finalize|finish|confirmar|enviar|pagar|comprar|finalizar)/i;",
    "    const safeAdvance = /(book|reserve|reservation|reservar|reserva|schedule|appointment|availability|select|choose|continue|next|cita|seleccionar|elegir|continuar|siguiente)/i;",
    "    const blocker = /(cookie|privacy|learn more|close|cancel|delete|remove|unsubscribe|login|sign in|share|map|directions|instagram|facebook|whatsapp)/i;",
    "    const rows = nodes",
    "      .map((element, index) => {",
    "        const input = element as HTMLInputElement;",
    "        const text = compact(element.textContent) || compact(input.value) || compact(element.getAttribute(\"aria-label\")) || compact(element.getAttribute(\"title\"));",
    "        const href = element instanceof HTMLAnchorElement ? element.href : undefined;",
    "        const selector = selectorFor(element);",
    "        const context = element.closest(\"li, article, section, [role='listitem'], [data-testid*='service'], [class*='service'], [class*='card'], [class*='item']\") || element.parentElement;",
    "        const nearText = compact(context?.textContent);",
    "        const disabled = (element as HTMLButtonElement | HTMLInputElement).disabled || element.getAttribute(\"aria-disabled\") === \"true\";",
    "        const visible = Boolean((element as HTMLElement).offsetWidth || (element as HTMLElement).offsetHeight || (element as HTMLElement).getClientRects().length);",
    "        const combined = `${text ?? \"\"} ${href ?? \"\"}`;",
    "        let score = 0;",
    "        if (actionable.test(combined)) score += 20;",
    "        if (element.tagName.toLowerCase() === \"button\") score += 5;",
    "        if ((element.getAttribute(\"type\") ?? \"\").toLowerCase() === \"submit\") score += 10;",
    "        if (safeAdvance.test(combined) && !finalCommit.test(combined)) score += 8;",
    "        if (nearText && nearText !== text && /(€|\\$|\\b\\d+\\s*(?:min|h)\\b|service|services|servicio|servicios|haircut|corte|beard|barba|appointment|cita)/i.test(nearText)) score += 12;",
    "        if (finalCommit.test(combined)) score += 2;",
    "        if (blocker.test(combined)) score -= 25;",
    "        if (disabled || !visible) score -= 15;",
    "        const kind = finalCommit.test(combined) ? \"final_commit\" : safeAdvance.test(combined) ? \"safe_advance\" : \"generic_action\";",
    "        return {",
    "          index,",
    "          tagName: element.tagName.toLowerCase(),",
    "          type: element.getAttribute(\"type\") || undefined,",
    "          text,",
    "          href,",
    "          selector,",
    "          nearText,",
    "          disabled,",
    "          visible,",
    "          score,",
    "          kind,",
    "          safeAdvance: kind === \"safe_advance\",",
    "        };",
    "      })",
    "      .filter((candidate) => candidate.score > 0 && (candidate.text || candidate.selector || candidate.href));",
    "    const selectorCounts = new Map<string, number>();",
    "    const withOrdinals = rows.map((candidate) => {",
    "      const key = String(candidate.selector ?? \"\");",
    "      const selectorOrdinal = key ? selectorCounts.get(key) ?? 0 : undefined;",
    "      if (key) selectorCounts.set(key, (selectorOrdinal ?? 0) + 1);",
    "      return { ...candidate, candidateIndex: candidate.index, selectorOrdinal };",
    "    });",
    "    return withOrdinals",
    "      .sort((left, right) => right.score - left.score || left.index - right.index)",
    "      .slice(0, Number(max));",
    "  }, limit).catch(() => []);",
    "}",
    "",
    "function parseInput(input: Record<string, unknown>): { ok: true; value: ParsedInput } | { ok: false; error: string } {",
    "  const url = stringValue(input.url);",
    "  if (url) {",
    "    const checked = httpUrl(url);",
    "    if (!checked.ok) return { ok: false, error: checked.error };",
    "  }",
    "  const commands = Array.isArray(input.commands) ? input.commands.filter(isRecord) : [];",
    "  const maxCommands = clampInteger(input.maxCommands, 20, 1, 40);",
    "  if (commands.length > maxCommands) return { ok: false, error: `commands exceeds maxCommands (${maxCommands})` };",
    "  return {",
    "    ok: true,",
    "    value: {",
    "      url,",
    "      commands,",
    "      prepareOnly: input.prepareOnly !== false,",
    "      width: clampInteger(input.width, 1280, 320, 3840),",
    "      height: clampInteger(input.height, 720, 240, 2160),",
    "      timeoutMs: clampInteger(input.timeoutMs, 30000, 1000, 60000),",
    "      maxCommands,",
    "    },",
    "  };",
    "}",
    "",
    "async function locatorFor(page: Page, command: BrowserCommand): Promise<Locator | undefined> {",
    "  const ordinal = optionalNonNegativeInteger(command.selectorOrdinal ?? command.ordinal);",
    "  for (const locator of locatorCandidatesFor(page, command)) {",
    "    const count = await locator.count().catch(() => 0);",
    "    if (count <= 0) continue;",
    "    if (ordinal !== undefined && count > ordinal) return locator.nth(ordinal);",
    "    if (ordinal === undefined || count === 1) return locator.first();",
    "  }",
    "  return undefined;",
    "}",
    "",
    "function locatorCandidatesFor(page: Page, command: BrowserCommand): Locator[] {",
    "  const locators: Locator[] = [];",
    "  const texts = stringValues(command.text, command.name, command.texts, command.names);",
    "  for (const selector of stringValues(command.selector, command.selectors)) {",
    "    const base = page.locator(selector);",
    "    for (const text of texts) locators.push(base.filter({ hasText: new RegExp(escapeRegex(text), \"i\") }));",
    "    locators.push(base);",
    "  }",
    "  for (const label of stringValues(command.label, command.labels)) locators.push(page.getByLabel(label, { exact: false }));",
    "  for (const placeholder of stringValues(command.placeholder, command.placeholders)) locators.push(page.getByPlaceholder(placeholder, { exact: false }));",
    "  for (const testId of stringValues(command.testId, command.testIds)) locators.push(page.getByTestId(testId));",
    "  const role = stringValue(command.role);",
    "  for (const text of texts) {",
    "    if (role) locators.push(page.getByRole(role as never, { name: new RegExp(escapeRegex(text), \"i\") }));",
    "    locators.push(page.getByText(text, { exact: false }));",
    "  }",
    "  return locators;",
    "}",
    "",
    "async function dismissCommonDialogs(page: Page): Promise<boolean> {",
    "  const commonSelectors = [",
    "    \"#CybotCookiebotDialogBodyButtonDecline\",",
    "    \"#CybotCookiebotDialogBodyLevelButtonLevelOptinDeclineAll\",",
    "    \"#onetrust-reject-all-handler\",",
    "    \"#onetrust-accept-btn-handler\",",
    "    \"button[data-testid='uc-deny-all-button']\",",
    "    \"button[data-testid='uc-accept-all-button']\",",
    "    \"button[aria-label='Reject all']\",",
    "    \"button[aria-label='Accept all']\",",
    "  ];",
    "  const labels = [/^(reject all|reject|decline|deny|no thanks)$/i, /^(accept all|accept|agree|i agree|allow all|ok)$/i, /^(close|dismiss)$/i];",
    "  for (const frame of page.frames()) {",
    "    for (const selector of commonSelectors) {",
    "      if (await clickAndVerifyDialogDismissed(page, frame.locator(selector).first())) return true;",
    "    }",
    "    for (const label of labels) {",
    "      const locators = [",
    "        frame.getByRole(\"button\", { name: label }).first(),",
    "        frame.getByRole(\"link\", { name: label }).first(),",
    "        frame.locator(\"button, [role='button'], a\").filter({ hasText: label }).first(),",
    "      ];",
    "      for (const locator of locators) {",
    "        if (await clickAndVerifyDialogDismissed(page, locator)) return true;",
    "      }",
    "    }",
    "  }",
    "  return false;",
    "}",
    "",
    "async function clickAndVerifyDialogDismissed(page: Page, locator: Locator): Promise<boolean> {",
    "  if (!(await clickIfVisible(locator))) return false;",
    "  await page.waitForTimeout(400).catch(() => undefined);",
    "  return !(await hasVisibleConsentDialog(page));",
    "}",
    "",
    "async function hasVisibleConsentDialog(page: Page): Promise<boolean> {",
    "  const dialogText = /(this website uses cookies|we use cookies|cookiebot|privacy preferences|cookie settings|consent)/i;",
    "  for (const frame of page.frames()) {",
    "    const visible = await frame.getByText(dialogText).first().isVisible({ timeout: 200 }).catch(() => false);",
    "    if (visible) return true;",
    "  }",
    "  return false;",
    "}",
    "",
    "async function clickIfVisible(locator: Locator): Promise<boolean> {",
    "  const visible = await locator.isVisible({ timeout: 500 }).catch(() => false);",
    "  if (!visible) return false;",
    "  try {",
    "    await locator.click({ timeout: 1500 });",
    "    return true;",
    "  } catch {",
    "    try {",
    "      await locator.click({ timeout: 1500, force: true });",
    "      return true;",
    "    } catch {",
    "      return locator.evaluate((element) => {",
    "        if (!(element instanceof HTMLElement)) return false;",
    "        element.click();",
    "        return true;",
    "      }).catch(() => false);",
    "    }",
    "  }",
    "}",
    "",
    "function browserLaunchOptions() {",
    "  const executablePath = resolveExecutablePath();",
    "  const base = { headless: true, args: [\"--no-sandbox\", \"--disable-dev-shm-usage\", \"--disable-gpu\"] };",
    "  return executablePath ? { ...base, executablePath } : base;",
    "}",
    "",
    "function resolveExecutablePath(): string | undefined {",
    "  const candidates = [",
    "    process.env.CHROMIUM_PATH,",
    "    process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,",
    "    \"/usr/bin/chromium\",",
    "    \"/usr/bin/chromium-browser\",",
    "    ...playwrightCacheCandidates(),",
    "    chromium.executablePath(),",
    "  ].filter((value): value is string => typeof value === \"string\" && value.trim().length > 0);",
    "  return candidates.find((candidate) => existsSync(candidate));",
    "}",
    "",
    "function playwrightCacheCandidates(): string[] {",
    "  const roots = [",
    "    process.env.PLAYWRIGHT_BROWSERS_PATH && process.env.PLAYWRIGHT_BROWSERS_PATH !== \"0\" ? process.env.PLAYWRIGHT_BROWSERS_PATH : undefined,",
    "    join(homedir(), \"Library\", \"Caches\", \"ms-playwright\"),",
    "    join(homedir(), \".cache\", \"ms-playwright\"),",
    "  ].filter((value): value is string => typeof value === \"string\" && value.trim().length > 0);",
    "  const candidates: string[] = [];",
    "  for (const root of roots) {",
    "    if (!existsSync(root)) continue;",
    "    for (const entry of safeReadDir(root)) {",
    "      if (!entry.startsWith(\"chromium-\")) continue;",
    "      candidates.push(",
    "        join(root, entry, \"chrome-mac-arm64\", \"Google Chrome for Testing.app\", \"Contents\", \"MacOS\", \"Google Chrome for Testing\"),",
    "        join(root, entry, \"chrome-mac\", \"Google Chrome for Testing.app\", \"Contents\", \"MacOS\", \"Google Chrome for Testing\"),",
    "        join(root, entry, \"chrome-linux\", \"chrome\"),",
    "      );",
    "    }",
    "  }",
    "  return candidates;",
    "}",
    "",
    "function safeReadDir(path: string): string[] {",
    "  try { return readdirSync(path); } catch { return []; }",
    "}",
    "",
    "function commandName(command: BrowserCommand): string {",
    "  return String(command.action ?? command.type ?? \"\").replace(/[^a-zA-Z]/g, \"\").toLowerCase();",
    "}",
    "",
    "function targetText(command: BrowserCommand): string {",
    "  return stringValues(",
    "    command.selector,",
    "    command.selectors,",
    "    command.text,",
    "    command.texts,",
    "    command.name,",
    "    command.names,",
    "    command.label,",
    "    command.labels,",
    "    command.placeholder,",
    "    command.placeholders,",
    "    command.testId,",
    "    command.testIds,",
    "    command.role,",
    "  ).join(\" \");",
    "}",
    "",
    "function optionalSkip(index: number, action: string, command: BrowserCommand, detail: string): StepRecord | undefined {",
    "  return booleanValue(command.optional) ? ok(index, action, `optional skipped: ${detail}`) : undefined;",
    "}",
    "",
    "function httpUrl(value: string): { ok: true; url: string } | { ok: false; error: string } {",
    "  try {",
    "    const url = new URL(value);",
    "    if (url.protocol !== \"http:\" && url.protocol !== \"https:\") return { ok: false, error: \"url must use http or https\" };",
    "    return { ok: true, url: url.toString() };",
    "  } catch {",
    "    return { ok: false, error: \"url must be a valid URL\" };",
    "  }",
    "}",
    "",
    "function ok(index: number, action: string, detail: string): StepRecord {",
    "  return { index, action, ok: true, detail };",
    "}",
    "",
    "function fail(index: number, action: string, detail: string): StepRecord {",
    "  return { index, action, ok: false, detail };",
    "}",
    "",
    "function stringValue(value: unknown): string | undefined {",
    "  return typeof value === \"string\" && value.trim() ? value.trim() : undefined;",
    "}",
    "",
    "function stringValues(...values: unknown[]): string[] {",
    "  const out: string[] = [];",
    "  for (const value of values) {",
    "    if (Array.isArray(value)) {",
    "      for (const item of value) {",
    "        const text = stringValue(item);",
    "        if (text && !out.includes(text)) out.push(text);",
    "      }",
    "      continue;",
    "    }",
    "    const text = stringValue(value);",
    "    if (text && !out.includes(text)) out.push(text);",
    "  }",
    "  return out;",
    "}",
    "",
    "function booleanValue(value: unknown): boolean {",
    "  return value === true;",
    "}",
    "",
    "function optionalNonNegativeInteger(value: unknown): number | undefined {",
    "  const numberValue = typeof value === \"number\" ? value : typeof value === \"string\" && value.trim() ? Number(value) : NaN;",
    "  if (!Number.isInteger(numberValue) || numberValue < 0) return undefined;",
    "  return numberValue;",
    "}",
    "",
    "function isRecord(value: unknown): value is BrowserCommand {",
    "  return Boolean(value) && typeof value === \"object\" && !Array.isArray(value);",
    "}",
    "",
    "function clampInteger(value: unknown, fallback: number, min: number, max: number): number {",
    "  const numberValue = typeof value === \"number\" && Number.isFinite(value) ? Math.floor(value) : fallback;",
    "  return Math.min(max, Math.max(min, numberValue));",
    "}",
    "",
    "function compactText(value: string, limit: number): string {",
    "  return value.replace(/\\s+/g, \" \").trim().slice(0, limit);",
    "}",
    "",
    "function safeFilename(value: string): string {",
    "  const clean = value.replace(/[^a-zA-Z0-9._-]+/g, \"-\").replace(/^-+|-+$/g, \"\").slice(0, 120);",
    "  return clean.endsWith(\".png\") ? clean : `${clean || \"browser\"}.png`;",
    "}",
    "",
    "function slugForFilename(value: string): string {",
    "  return value.toLowerCase().replace(/[^a-z0-9]+/g, \"-\").replace(/^-+|-+$/g, \"\").slice(0, 80) || \"browser\";",
    "}",
    "",
    "function escapeRegex(value: string): string {",
    "  return value.replace(/[.*+?^${}()|[\\]\\\\]/g, \"\\\\$&\");",
    "}",
    "",
  ].join("\n");
}
