import type { ToolPackageManifest } from "./toolPackage.js";
import type { ToolCreationV1Result } from "./toolCreationV1.js";

export function renderBrowserScreenshotToolSource(
  input: ToolCreationV1Result["input"],
  manifest: Omit<ToolPackageManifest, "package">,
): string {
  return [
    "import { existsSync, readdirSync } from \"node:fs\";",
    "import { homedir } from \"node:os\";",
    "import { join } from \"node:path\";",
    "import { chromium } from \"playwright-core\";",
    "import type { Tool } from \"../tool.js\";",
    "",
    `const inputSchema: Tool["inputSchema"] = ${JSON.stringify(manifest.inputSchema, null, 2)};`,
    `const outputSchema: Tool["outputSchema"] = ${JSON.stringify(manifest.outputSchema, null, 2)};`,
    "",
    "type WaitUntil = \"load\" | \"domcontentloaded\" | \"networkidle\";",
    "",
    "export const tool: Tool = {",
    `  name: ${JSON.stringify(input.name)},`,
    `  displayName: ${JSON.stringify(input.displayName)},`,
    `  version: ${JSON.stringify(input.version)},`,
    `  description: ${JSON.stringify(input.description)},`,
    `  capabilities: ${JSON.stringify(input.capabilities)},`,
    `  startupMode: ${JSON.stringify(manifest.startupMode)},`,
    "  inputSchema,",
    "  outputSchema,",
    "  async healthcheck() {",
    "    const executablePath = resolveExecutablePath();",
    "    return {",
    "      ok: true,",
    "      detail: executablePath",
    "        ? `Browser screenshot tool loaded; Chromium executable found at ${executablePath}.`",
    "        : \"Browser screenshot tool loaded; Playwright will resolve the Chromium executable at runtime.\",",
    "    };",
    "  },",
    "  async run(input) {",
    "    const parsed = parseInput(input);",
    "    if (!parsed.ok) return { ok: false, content: parsed.error };",
    "    const launchOptions = browserLaunchOptions();",
    "    const browser = await chromium.launch(launchOptions);",
    "    try {",
    "      const page = await browser.newPage({ viewport: { width: parsed.width, height: parsed.height } });",
    "      await page.goto(parsed.url, { waitUntil: parsed.waitUntil, timeout: parsed.timeoutMs });",
    "      await dismissCommonConsentDialogs(page);",
    "      await focusPage(page, parsed);",
    "      await dismissCommonConsentDialogs(page);",
    "      const title = await page.title();",
    "      const finalUrl = page.url();",
    "      const buffer = await page.screenshot({ fullPage: parsed.fullPage, type: \"png\" });",
    "      const filename = parsed.filename ?? `${slugForFilename(new URL(finalUrl).hostname || \"screenshot\")}.png`;",
    "      return {",
    "        ok: true,",
    "        content: `Screenshot captured: ${finalUrl}` ,",
    "        data: {",
    "          url: finalUrl,",
    "          title,",
    "          width: parsed.width,",
    "          height: parsed.height,",
    "          fullPage: parsed.fullPage,",
    "          focusText: parsed.focusText,",
    "          selector: parsed.selector,",
    "          artifact: {",
    "            filename,",
    "            mimeType: \"image/png\",",
    "            contentBase64: buffer.toString(\"base64\"),",
    "            description: `${parsed.fullPage ? \"Full-page\" : \"Viewport\"} screenshot captured from ${finalUrl}`",
    "          }",
    "        }",
    "      };",
    "    } finally {",
    "      await browser.close();",
    "    }",
    "  },",
    "};",
    "",
    "function browserLaunchOptions() {",
    "  const executablePath = resolveExecutablePath();",
    "  const base = {",
    "    headless: true,",
    "    args: [\"--no-sandbox\", \"--disable-dev-shm-usage\", \"--disable-gpu\"],",
    "  };",
    "  return executablePath ? { ...base, executablePath } : base;",
    "}",
    "",
    "function resolveExecutablePath(): string | undefined {",
    "  const candidates = [",
    "    process.env.CHROMIUM_PATH,",
    "    process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,",
    "    \"/usr/bin/chromium\",",
    "    \"/usr/bin/chromium-browser\",",
    "    ...playwrightCacheCandidates(),",
    "    chromium.executablePath(),",
    "  ].filter((value): value is string => typeof value === \"string\" && value.trim().length > 0);",
    "  return candidates.find((candidate) => existsSync(candidate));",
    "}",
    "",
    "function playwrightCacheCandidates(): string[] {",
    "  const roots = [",
    "    process.env.PLAYWRIGHT_BROWSERS_PATH && process.env.PLAYWRIGHT_BROWSERS_PATH !== \"0\" ? process.env.PLAYWRIGHT_BROWSERS_PATH : undefined,",
    "    join(homedir(), \"Library\", \"Caches\", \"ms-playwright\"),",
    "    join(homedir(), \".cache\", \"ms-playwright\"),",
    "  ].filter((value): value is string => typeof value === \"string\" && value.trim().length > 0);",
    "  const candidates: string[] = [];",
    "  for (const root of roots) {",
    "    if (!existsSync(root)) continue;",
    "    for (const entry of safeReadDir(root)) {",
    "      if (!entry.startsWith(\"chromium-\")) continue;",
    "      candidates.push(",
    "        join(root, entry, \"chrome-mac-arm64\", \"Google Chrome for Testing.app\", \"Contents\", \"MacOS\", \"Google Chrome for Testing\"),",
    "        join(root, entry, \"chrome-mac\", \"Google Chrome for Testing.app\", \"Contents\", \"MacOS\", \"Google Chrome for Testing\"),",
    "        join(root, entry, \"chrome-linux\", \"chrome\"),",
    "      );",
    "    }",
    "  }",
    "  return candidates;",
    "}",
    "",
    "function safeReadDir(path: string): string[] {",
    "  try {",
    "    return readdirSync(path);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "async function dismissCommonConsentDialogs(page: import(\"playwright-core\").Page): Promise<void> {",
    "  const labels = [",
    "    /^(accept all|accept|i agree|agree|consent|allow all|ok)$/i,",
    "    /^(reject all|reject|decline|deny|do not consent|no thanks|continue without accepting)$/i,",
    "    /^(принять|принять все|согласен|согласиться|разрешить все|ок)$/i,",
    "    /^(отклонить|отклонить все|не принимаю|отказаться)$/i,",
    "    /^(прийняти|прийняти все|відхилити|відхилити все|погоджуюсь)$/i,",
    "  ];",
    "  for (let pass = 0; pass < 4; pass += 1) {",
    "    await page.waitForTimeout(pass === 0 ? 1200 : 500).catch(() => undefined);",
    "    for (const frame of page.frames()) {",
    "      if (await dismissConsentInFrame(frame, labels)) {",
    "        await page.waitForTimeout(800).catch(() => undefined);",
    "        return;",
    "      }",
    "    }",
    "  }",
    "}",
    "",
    "async function dismissConsentInFrame(",
    "  frame: import(\"playwright-core\").Frame,",
    "  labels: RegExp[],",
    "): Promise<boolean> {",
    "  for (const label of labels) {",
    "    const locators = [",
    "      frame.getByRole(\"button\", { name: label }).first(),",
    "      frame.getByRole(\"link\", { name: label }).first(),",
    "      frame.locator(\"button\").filter({ hasText: label }).first(),",
    "      frame.locator(\"[role='button']\").filter({ hasText: label }).first(),",
    "      frame.getByText(label).first(),",
    "    ];",
    "    for (const locator of locators) {",
    "      if (await clickIfVisible(locator)) return true;",
    "    }",
    "  }",
    "  const dialogSelectors = [",
    "    \"[role='dialog']\",",
    "    \"[aria-modal='true']\",",
    "    \"[class*='cookie']\",",
    "    \"[class*='consent']\",",
    "    \"[id*='cookie']\",",
    "    \"[id*='consent']\",",
    "  ];",
    "  for (const selector of dialogSelectors) {",
    "    const dialog = frame.locator(selector).filter({ hasText: /(cookie|consent|privacy|соглас|cookie|куки|файлов cookie)/i }).first();",
    "    const visible = await dialog.isVisible({ timeout: 300 }).catch(() => false);",
    "    if (!visible) continue;",
    "    for (const label of labels) {",
    "      const action = dialog.locator(\"button, [role='button'], a\").filter({ hasText: label }).first();",
    "      if (await clickIfVisible(action)) return true;",
    "    }",
    "  }",
    "  const close = frame.locator(\"button[aria-label*='close' i], button[aria-label*='dismiss' i], button[aria-label*='закрыть' i]\").first();",
    "  return clickIfVisible(close);",
    "}",
    "",
    "async function clickIfVisible(locator: import(\"playwright-core\").Locator): Promise<boolean> {",
    "  const visible = await locator.isVisible({ timeout: 500 }).catch(() => false);",
    "  if (!visible) return false;",
    "  await locator.scrollIntoViewIfNeeded({ timeout: 1000 }).catch(() => undefined);",
    "  await locator.click({ timeout: 2000 }).catch(() => undefined);",
    "  return true;",
    "}",
    "",
    "async function focusPage(page: import(\"playwright-core\").Page, parsed: Extract<ReturnType<typeof parseInput>, { ok: true }>): Promise<void> {",
    "  if (parsed.selector) {",
    "    const locator = page.locator(parsed.selector).first();",
    "    await locator.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => undefined);",
    "  } else if (parsed.focusText) {",
    "    const locator = page.getByText(parsed.focusText, { exact: false }).first();",
    "    await locator.scrollIntoViewIfNeeded({ timeout: 3000 }).catch(() => undefined);",
    "  }",
    "  await page.waitForTimeout(500).catch(() => undefined);",
    "}",
    "",
    "function parseInput(input: Record<string, unknown>):",
    "  | { ok: true; url: string; fullPage: boolean; focusText?: string; selector?: string; width: number; height: number; waitUntil: WaitUntil; timeoutMs: number; filename?: string }",
    "  | { ok: false; error: string } {",
    "  const rawUrl = typeof input.url === \"string\" ? input.url.trim() : \"\";",
    "  if (!rawUrl) return { ok: false, error: \"url is required\" };",
    "  let url: URL;",
    "  try {",
    "    url = new URL(rawUrl);",
    "  } catch {",
    "    return { ok: false, error: \"url must be a valid URL\" };",
    "  }",
    "  if (url.protocol !== \"http:\" && url.protocol !== \"https:\") {",
    "    return { ok: false, error: \"url must use http or https\" };",
    "  }",
    "  const waitUntil = parseWaitUntil(input.waitUntil);",
    "  if (!waitUntil) return { ok: false, error: \"waitUntil must be load, domcontentloaded, or networkidle\" };",
    "  return {",
    "    ok: true,",
    "    url: url.toString(),",
    "    fullPage: typeof input.fullPage === \"boolean\" ? input.fullPage : false,",
    "    focusText: typeof input.focusText === \"string\" && input.focusText.trim() ? input.focusText.trim().slice(0, 200) : undefined,",
    "    selector: typeof input.selector === \"string\" && input.selector.trim() ? input.selector.trim().slice(0, 300) : undefined,",
    "    width: clampInteger(input.width, 1280, 320, 3840),",
    "    height: clampInteger(input.height, 720, 240, 2160),",
    "    waitUntil,",
    "    timeoutMs: clampInteger(input.timeoutMs, 30000, 1000, 60000),",
    "    filename: typeof input.filename === \"string\" && input.filename.trim() ? safeFilename(input.filename) : undefined,",
    "  };",
    "}",
    "",
    "function parseWaitUntil(value: unknown): WaitUntil | undefined {",
    "  if (value === undefined) return \"load\";",
    "  return value === \"load\" || value === \"domcontentloaded\" || value === \"networkidle\" ? value : undefined;",
    "}",
    "",
    "function clampInteger(value: unknown, fallback: number, min: number, max: number): number {",
    "  const numberValue = typeof value === \"number\" && Number.isFinite(value) ? Math.floor(value) : fallback;",
    "  return Math.min(max, Math.max(min, numberValue));",
    "}",
    "",
    "function safeFilename(value: string): string {",
    "  const cleaned = value.trim().replace(/[^a-z0-9._-]+/gi, \"-\").replace(/^-+|-+$/g, \"\");",
    "  return cleaned.toLowerCase().endsWith(\".png\") ? cleaned : `${cleaned || \"screenshot\"}.png`;",
    "}",
    "",
    "function slugForFilename(value: string): string {",
    "  return value.toLowerCase().replace(/[^a-z0-9]+/g, \"-\").replace(/^-+|-+$/g, \"\") || \"screenshot\";",
    "}",
    "",
  ].join("\n");
}

