export function telegramFormattingSourceLines(): string[] {
  return [
    "type TelegramTextMessage = { text: string; parse_mode?: \"HTML\" };",
    "",
    "function telegramMessageFromMarkdown(input: string): TelegramTextMessage {",
    "  const converted = markdownToTelegramHtml(input);",
    "  return converted.trim() ? { text: converted.slice(0, 3900), parse_mode: \"HTML\" } : { text: input.slice(0, 3900) };",
    "}",
    "",
    "function markdownToTelegramHtml(input: string): string {",
    "  const holds: string[] = [];",
    "  const hold = (html: string) => {",
    "    const key = `@@HTML_HOLD_${holds.length}@@`;",
    "    holds.push(html);",
    "    return key;",
    "  };",
    "  let text = normalizeMarkdownTables(input);",
    "  text = text.replace(/```([\\s\\S]*?)```/g, (_match, code: string) => hold(`<pre>${escapeHtml(code.trim())}</pre>`));",
    "  text = text.replace(/`([^`]+)`/g, (_match, code: string) => hold(`<code>${escapeHtml(code)}</code>`));",
    "  text = text.replace(/!\\[([^\\]]*)\\]\\(([^)]+)\\)/g, (_match, label: string) => label ? hold(`<i>${escapeHtml(label)}</i>`) : \"\");",
    "  text = text.replace(/\\[([^\\]]+)\\]\\((https?:\\/\\/[^)\\s]+)\\)/g, (_match, label: string, url: string) => hold(`<a href=\"${escapeHtml(url)}\">${escapeHtml(label)}</a>`));",
    "  text = escapeHtml(text);",
    "  text = text.replace(/^#{1,6}\\s+(.+)$/gm, \"<b>$1</b>\");",
    "  text = text.replace(/\\*\\*([^*\\n]+)\\*\\*/g, \"<b>$1</b>\");",
    "  text = text.replace(/__([^_\\n]+)__/g, \"<b>$1</b>\");",
    "  text = text.replace(/(^|[^*])\\*([^*\\n]+)\\*(?!\\*)/g, \"$1<i>$2</i>\");",
    "  text = text.replace(/(^|[^_])_([^_\\n]+)_(?!_)/g, \"$1<i>$2</i>\");",
    "  text = text.replace(/^\\s*[-*]\\s+/gm, \"• \");",
    "  text = text.replace(/^\\s*\\d+[.)]\\s+/gm, \"• \");",
    "  text = text.replace(/^\\s*&gt;\\s?(.+)$/gm, \"<blockquote>$1</blockquote>\");",
    "  holds.forEach((html, index) => { text = text.replaceAll(`@@HTML_HOLD_${index}@@`, html); });",
    "  return text.replace(/\\n{3,}/g, \"\\n\\n\").trim();",
    "}",
    "",
    "function normalizeMarkdownTables(input: string): string {",
    "  const lines = input.split(/\\r?\\n/);",
    "  const output: string[] = [];",
    "  for (let index = 0; index < lines.length; index += 1) {",
    "    if (isMarkdownTableStart(lines, index)) {",
    "      const headers = splitTableRow(lines[index]!);",
    "      index += 2;",
    "      while (index < lines.length && lines[index]!.includes(\"|\")) {",
    "        const cells = splitTableRow(lines[index]!);",
    "        output.push(headers.map((header, cellIndex) => `${header}: ${cells[cellIndex] ?? \"\"}`).join(\"; \"));",
    "        index += 1;",
    "      }",
    "      index -= 1;",
    "      continue;",
    "    }",
    "    output.push(lines[index]!);",
    "  }",
    "  return output.join(\"\\n\");",
    "}",
    "",
    "function isMarkdownTableStart(lines: string[], index: number): boolean {",
    "  const current = lines[index] ?? \"\";",
    "  const next = lines[index + 1] ?? \"\";",
    "  return current.includes(\"|\") && /^\\s*\\|?\\s*:?-{3,}:?\\s*(\\|\\s*:?-{3,}:?\\s*)+\\|?\\s*$/.test(next);",
    "}",
    "",
    "function splitTableRow(row: string): string[] {",
    "  return row.trim().replace(/^\\|/, \"\").replace(/\\|$/, \"\").split(\"|\").map((cell) => cell.trim()).filter(Boolean);",
    "}",
    "",
    "function escapeHtml(value: string): string {",
    "  return value.replace(/&/g, \"&amp;\").replace(/</g, \"&lt;\").replace(/>/g, \"&gt;\").replace(/\"/g, \"&quot;\");",
    "}",
    "",
  ];
}
